### ISSUE TITLE
Suggestion: Note support for cookies in documents

### ISSUE THREAD

**Issue by turtlegood** [joltup/rn-fetch-blob#100]
Thank you for your wonderful project! I have a small suggestion: Currently, the documentation does not say anything about cookie support (I tried to ctrl+F to search "cookie" but failed). However, after some experiment, I find that it automatically shares the cookie in react native. It is very helpful for those applications based on cookies such as authentication. Therefore, I suggest that the document add several sentences, *explicitly* saying that it has cookie support.

**Comment by Traviskn** [comment]
We are open to PRs both to our README and our Wiki, I'd be glad to accept a PR to update our docs 😃

**Comment by turtlegood** [comment]
OK I will do that 😃

**Comment by turtlegood** [comment]
created https://github.com/joltup/rn-fetch-blob/pull/110 😃
