### ISSUE TITLE
Downloaded files no found at location returned: /data/user/0/com.myapp.rn/files/... or /data/data/com.myapp.rn/files

### ISSUE THREAD

**Issue by schumannd** [joltup/rn-fetch-blob#103]
We are experiencing errors only on android, and mostly with samsung phones:

```
Error: source file : /data/user/0/com.myapp.rn/files/1.mp3not exists
```

Has anyone experienced something similar? Is the `/data/user/0/` path even valid? How can this happen? Maybe through users not having enough free space?

**Comment by schumannd** [comment]
I am getting records of this error through sentry, so I don't know the exact circumstances.

But in general the app downloads multiple files using this package. It awaits all promises and then operates on these files. So I would expect the promise to only return a file path, which actually exists. These operations also happen right after eachother, so for the file to have been deleted in between is highly unlikely.

**Comment by schumannd** [comment]
nevermind, I was actually deleteing the files in between.

**Comment by schumannd** [comment]
Go through your code where files are created/downloaded and manipulated. Make sure this piece of code cannot be called multiple times and does not interfere with itself. Manually make sure the files you think exist actually exist. Good luck

**Comment by schumannd** [comment]
Actually we are still getting this error occasionally. I suspect some android devices to falsely claim a file was downloaded successfully when it wasn't. We now manually check for the existence of the file and trigger a redownload if it does not exist.

**Comment by fukemy** [comment]
same problem here
