### ISSUE TITLE
can not download a file over 2GB

### ISSUE THREAD

**Issue by yezhou** [joltup/rn-fetch-blob#105]
it seems like a file length int32 problem. the task.progress can not report correctly when a file is over 2gb. both ios and android are not working.

when the content length over 2gb, the total length of content( second parameter of the progress function) will show a negative number.

 it should be a classic problem, which use int32 in the code. please find a way to fix it, thanks!

**Comment by Traviskn** [comment]
It sounds like you may know how to fix this problem. We are always open to PRs 😄
