### ISSUE TITLE
Upload Video file more than 5mb to firebase storage

### ISSUE THREAD

**Issue by AbdulRayhman** [joltup/rn-fetch-blob#107]
If i upload video which is 4.5 mb or less, it upload on firebase storage no issue with that if the video size more than 4.5mb the build Blob is not working and application crash.
How can i build blob for large files to upload file on firebase storage?

This is my Upload Video function after i compress the video.
------> Upload Video Func

  uploadVideoToStorage = (uri, mime = 'video/mp4') => {
    console.log("Upload the Video.....");

    return new Promise((resolve, reject) => {
      console.log(uri, mime);
        let tempPath= '/storage'+this.state.imageURI.split('storage')[1];
        tempPath= tempPath.split('.mp4')[0]+'_c';
        tempPath = tempPath+'.mp4';
        console.log("After Compressed");

        console.log(tempPath);
        RNFetchBlob.fs.exists(tempPath).then(res=>{
          console.log(res);

          if(res){//Check File Exists or Not

          const uploadUri = "file://"+tempPath.toString();
          console.log("Upload from Storage Path...",uploadUri);
          const sessionId = new Date().getTime();

          let uploadBlob = null;
          let storage = this.state.firebaseApp.storage();
          const imageRef = storage.ref('/posts').child('posts'+sessionId);
          console.log(imageRef, uploadUri);
          let data = '';
          // RNFetchBlob.fs.readFile(uploadUri, 'base64')

          const base64DataObj = new Promise((resolve, reject)=>{

              RNFetchBlob.fs.readStream(uploadUri, 'base64',102400)
              .then((ifstream) => {
                ifstream.open()
                ifstream.onData((chunk) => {
                  // when encoding is `ascii`, chunk will be an array contains numbers
                  // otherwise it will be a string
                  data += chunk
                })
                ifstream.onError((err) => {
                  console.log('oops', err)
                  reject(err);
                })
                ifstream.onEnd(async () => {  
                  console.log(data);
                  resolve(data);
                  // return data;
                })
              })
              .catch((error) => {
                console.log("Error....");
                console.log(error);
                reject(error);
            });

          });//Data Base 64 Promise
          base64DataObj.then((res)=>{
            console.log("Stream Promise Resolve ---> ", res);
            const buildBlob = new Promise((resolve,reject)=>{
              resolve(Blob.build(res, { type: `${mime};BASE64` }));
              reject('Blob not build perfectly.!');
            });
            buildBlob.then((res)=>{
              console.log(res);
              imageRef.put(res, { contentType: mime }).then((res)=>{
                console.log(res);
                resolve(imageRef.getDownloadURL());                
              }).catch((err)=>{
                console.log(err);
                reject(err);
              });
              
            })
            
          });
          }else{
            Alert.alert("Not Found","File not found!");
            this.setState({
              isUploadNow: false
            });
          }
          }).catch((err)=>{
            console.log(err);
          });
    });
  }

---> Package.json

{
	"name": "Greetme",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"firebase": "^4.5.0",
		"gl-react-imagefilters": "^0.1.5",
		"lodash": "^4.17.10",
		"moment": "^2.19.1",
		"native-base": "^2.3.3",
		"react": "16.0.0-alpha.12",
		"react-mixin": "^2.0.2",
		"react-moment": "^0.6.8",
		"react-native": "0.48.3",
		"react-native-animatable": "^1.2.4",
		"react-native-background-timer": "^1.3.0",
		"react-native-camera": "^0.6.0",
		"react-native-compress": "^2.0.1",
		"react-native-datepicker": "^1.6.0",
		"react-native-dimension": "^1.0.6",
		"react-native-display": "^1.0.8",
		"react-native-easy-grid": "^0.1.15",
		"react-native-extra-dimensions-android": "^0.21.0",
		"react-native-fast-image": "^1.0.0",
		"react-native-fcm": "^10.0.3",
		"react-native-geocoder": "^0.4.8",
		"react-native-image-picker": "^0.26.7",
		"react-native-immersive": "^1.1.0",
		"react-native-offline": "^3.8.0",
		"react-native-popover-tooltip": "^1.1.4",
		"react-native-popup-dialog": "^0.9.36",
		"react-native-pull-to-refresh": "^2.1.2",
		"react-native-push-notification": "^3.0.1",
		"react-native-rest-kit": "0.0.6",
		"react-native-simple-radio-button": "^2.6.2",
		"react-native-swiper": "^1.5.13",
		"react-native-textinput-effects": "^0.4.2",
		"react-native-thumbnail": "^1.1.0",
		"react-native-tooltip-menu": "^1.1.0",
		"react-native-vector-icons": "^4.4.0",
		"react-native-vertical-swipe": "^1.0.1",
		"react-native-video": "^2.0.0",
		"react-navigation": "^1.0.0-beta.13",
		"rn-fetch-blob": "^0.10.11"
	},
	"devDependencies": {
		"babel-jest": "21.0.2",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.1.0",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	},
	"rnpm": {
		"assets": [
			"./assets/fonts/"
		]
	}
}

**Comment by tombailey** [comment]
Is it possible that you can reproduce the issue and capture the logs from the native console? You can use either logcat for Android or XCode console for iOS

Does this happen on both Android and iOS?

**Comment by AbdulRayhman** [comment]
Resolve this issue by using only build blob not readFile from RNFetchBlob.

 Blob.build(rnfbURI, { type : 'video/mp4;'})
            .then((blob) => {
              // upload image using Firebase SDK
              this.state.firebaseApp.storage()
                .ref('posts')
                .child('posts'+sessionId)
                .put(blob, { contentType : 'video/mp4' })
                .then((snapshot) => {
                  console.log('Uploaded', snapshot.totalBytes, 'bytes.');
                  console.log(snapshot.metadata);
                  var url = snapshot.metadata.downloadURLs[0];
                  console.log('File available at', url);
                  this.setState({ pictureDisabled : false});
                  resolve(url);
                }).catch(function(error) {
                  console.error('Upload failed:', error);
                  this.setState({ pictureDisabled : false});
                });
              });

**Comment by Traviskn** [comment]
Glad you found a solution! I've always been very wary of creating base64 encoded representations of files, since for large files you can quickly run out of memory.
