### ISSUE TITLE
Creating a CSV File- UFT8

### ISSUE THREAD

**Issue by barnir** [joltup/rn-fetch-blob#109]
Hi,
I have installed "react-native": "^0.55.4" and "react-native-fetch-blob": "^0.10.8"

I'm using Fetch Blob to write a CSV File, but as we are portuguese we have letters like "ç", "É" 
As far as i can tell this characters are supported by UTF8, which is what i'm using.. but when checking the CSV file this kind of characters appear as ? 

 RNFetchBlob.fs .writeFile(path, csvString, 'utf-8')

Is it a but on format? i'm doing something wrong? Thank for the awsome package

**Comment by Traviskn** [comment]
How are you viewing the CSV file? It could be the code that is viewing the CSV that cannot understand the UTF-8 characters.

Would you be able to share an example code snippet that reproduces the error, or perhaps the file that has the error?

**Comment by barnir** [comment]
We are opening the CSV on Excell for example or the equivalent on MAC (dont remember the name of the app), inside the app we dont open the fire, we only create the strings for the file.. 

```
  // write the file
    RNFetchBlob
      .fs
      .writeFile(path, csvString, 'utf-8')
      .then(() => {
        Share
          .open({url: `file://${path}`})
          .then(() => {
            setTimeout(() => {
              RNFetchBlob
                .fs
                .unlink(path)
                .catch((err) => {
                  console.log(err);
                });
            }, 500);
          })
          .catch(err => {
            console.log(JSON.stringify(err));
          });
      })
      .catch((err) => {
        console.log(err.message);
      });
```

**Comment by barnir** [comment]
We found out it is probably excell.. will look into this.. will close :) thank you
