### ISSUE TITLE
java.lang.String com.facebook.react.bridge.ReadableMap.string(java.lang.string) on a null object Reference while uploading image to firebase

### ISSUE THREAD

**Issue by mohammdwaqas** [joltup/rn-fetch-blob#119]
i am getting above error while trying this code to upload image to firebase

`function uploadImage() {

            return new Promise((resolve, reject) => {
                let imgUri = 'content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F80/ORIGINAL/NONE/1685675380'; let uploadBlob = null;
                const uploadUri = Platform.OS === 'ios' ? imgUri.replace('file://', '') : imgUri;

                const imageRef = firebase.storage().ref();
                const name = 'myimg';
                mime = 'image/jpeg';
                fs.readFile(uploadUri, 'base64')
                    .then(data => {
                        return Blob.build(data, { type: `${mime};BASE64` });
                    })
                    .then(blob => {
                        uploadBlob = blob;
                        return imageRef.put(blob, { contentType: mime, name: name });
                    })
                    .then(() => {
                        uploadBlob.close()
                        return imageRef.getDownloadURL();
                    })
                    .then(url => {
                        resolve(url);
                    })
                    .catch(error => {
                        reject(error)
                    })
            })
        }`

dependencies: 

`"react-native": "^0.55.3",
    "react-native-firebase": "^4.1.0",
    "react-native-image-picker": "^0.26.10",
    "react-navigation": "^2.6.0",
    "rn-fetch-blob": "^0.10.11"`

any help ?
![snap](https://user-images.githubusercontent.com/26755222/42814442-a846c68a-89dd-11e8-9965-6668e6b94a02.PNG)

**Comment by ihavenoface5** [comment]
I found one place (addCompleteDownload) where getString was called on a ReadableMap without a check if the path key exists. I will submit a pull request.

**Comment by bsjaffer** [comment]
I am getting same issue when i add below code snippet . 
//
window.Blob = Blob;

**Comment by diesmori** [comment]
I just solved it following rainbarrel's solution at [https://github.com/wkh237/react-native-fetch-blob/issues/634](https://github.com/wkh237/react-native-fetch-blob/issues/634
), doing the same for window.Blob, because I got the "unsupported bodyinit type" error right after the mentioned solution.

**Comment by tram421** [comment]
You can try this:
replace: 
`const uploadUri = Platform.OS === 'ios' ? imgUri.replace('file://', '') : imgUri;`
To:
`const uploadUri = imgUri;`
This work for me (on android).
