### ISSUE TITLE
Image show half gray

### ISSUE THREAD

**Issue by JulienUsson** [joltup/rn-fetch-blob#130]
Hello,

Any news about this issue on the old repo? 
https://github.com/wkh237/react-native-fetch-blob/issues/622

I'm using rn-fetch-blob 0.10.12 and have this bug with bad network.

Thanks you

**Comment by jjayasagar** [comment]
Hi,

We have this issue for a while! Any update on this? 

Thank you so much!

**Comment by JulienUsson** [comment]
Using https://github.com/itinance/react-native-fs resolves my issue.
