### ISSUE TITLE
(Android) Upgrade SDK Build Tools to 25.0.0 or better

### ISSUE THREAD

**Issue by anvu69** [joltup/rn-fetch-blob#131]
Hi !
I have issue when build android. Pls upgrade SDK build tools to fix it. Sr my english so bad. Tks!!

`* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':rn-fetch-blob'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':rn-fetch-blob'. Minimum required is 25.0.0`

**Comment by anvu69** [comment]
Please merge pull request a4abef9 ! He fixed this bug

**Comment by cayasso** [comment]
Hi! Any update on this PR to be merged?

**Comment by mikehardy** [comment]
#129 is merged and fixes this, an npm install joltup/rn-fetch-blob to get the github master version I think

**Comment by cayasso** [comment]
Nice thank you!!!

**Comment by mikehardy** [comment]
I am only the messenger, but I hit this issue myself just this afternoon and how lucky was I that the PR was merged 1 hour before I hit it? Open source for the win...

**Comment by anvu69** [comment]
Ok i close issue. Nice PR
