### ISSUE TITLE
Android 7.0 download APK unsuccessfully

### ISSUE THREAD

**Issue by nc3816** [joltup/rn-fetch-blob#136]
I tried to use rn-fetch-blob to update my app (Android) APK, I follow the example of READ.ME but it always downloads the APK unsuccessfully. Please help me!

* please provide the version of installed library and RN project.
rn-fetch-blob:
RN: 0.49
android: 7.0

* a sample code snippet/repository is very helpful to spotting the problem.
Follow the READ.me API example

* issues 
In download manager, the download of the APK always unsuccessfully.

**Comment by nc3816** [comment]
Fixed and closed.

**Comment by meiqi1992** [comment]
@nc3816 need help

**Comment by nc3816** [comment]
@meiqi1992 you need to add path

Here is my code:

`updateAPP = () => {
        const android = RNFetchBlob.android;
        RNFetchBlob
        .config({
            addAndroidDownloads: {
            useDownloadManager: true,
            title: 'YOURAPPNAME.apk',
            description: 'An APK that will be installed',
            mime: 'application/vnd.android.package-archive',
            mediaScannable: true,
            notification: true,
            path: RNFetchBlob.fs.dirs.DownloadDir + "/YOURAPPNAME.apk"
            }
        })
        .fetch('GET', downloadAddress)
        .then((res) => {
            android.actionViewIntent(res.path(), 'application/vnd.android.package-archive');
        })
    }`

**Comment by meiqi1992** [comment]
@nc3816 tks very much, it worked fine

**Comment by nc3816** [comment]
@meiqi1992 You are welcome :)
