### ISSUE TITLE
upload file to AliyunOSS error

### ISSUE THREAD

**Issue by Jeijie** [joltup/rn-fetch-blob#152]
It's Ok in Android，but get error in IOS.

![qq 20180817094812](https://user-images.githubusercontent.com/9338052/44243688-fcd12780-a202-11e8-885c-63a75a0f4a88.png)

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 1.14 GB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.4 - /usr/local/bin/yarn
      npm: 6.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
    IDEs:
      Android Studio: 3.1 AI-173.4720617
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1

* a sample code snippet/repository 

let body =[
...,
{
              name: "file",
              filename: fileName,
              data: RNFetchBlob.wrap(file),
              type: "image/jpeg"
            }
]
RNFetchBlob.fetch("POST", res.host, {}, body)
            .uploadProgress((written, total) => {
              // console.warn('查找中', written, total)
            })
            .progress((received, total) => {
              let perent = received / total;
            })
            .then(response => {
              console.warn("result.", file, response);
            })
            .catch(error => {
                 console.warn("result.", file, response);
            });

**Comment by Jeijie** [comment]
![3d19efbc-3ae8-2cc0-cefc-650ce1760f9f](https://user-images.githubusercontent.com/9338052/44244050-90efbe80-a204-11e8-80c1-650791d9419a.jpg)

**Comment by onlybenyang** [comment]
@Traviskn I also have this issue, it work on Android normally, but ios failed to upload image. It seems not the error of server.

**Comment by onlybenyang** [comment]
@Jeijie  Do you find the reason and solution, could you share with us?

**Comment by Jeijie** [comment]
I solved by Using native  form and XMLHttpRequest.

**Comment by onlybenyang** [comment]
@Jeijie I find that the file uri on iOS should remove the file://. but after rn-fetch-blob wrap the uri, it still not find resource by the file uri. I not known iOS well. I will try to find the format of uri on iOS

**Comment by onlybenyang** [comment]
@Jeijie  thanks, your code works for me.
