### ISSUE TITLE
Support Android SDK 26--New Release

### ISSUE THREAD

**Issue by SunburtReynolds** [joltup/rn-fetch-blob#160]
Hey @Traviskn! Any chance you could create a new release? There have been a few critical updates merged into master since v0.10.12  that my team really needs. Specifically, we need to run the most recent version of React Native (0.56) which requires Android SDK 26. A commit to support this version of RN was merged here: https://github.com/joltup/rn-fetch-blob/blob/master/android/build.gradle#L21. We just need your help to create a release :)

Thanks so much.

**Comment by stsiushkevich** [comment]
I have the same issue!

**Comment by Traviskn** [comment]
I've just published v0.10.13 🎉
