### ISSUE TITLE
iOS downloaded images not showing

### ISSUE THREAD

**Issue by ashmortar** [joltup/rn-fetch-blob#180]
Hey all,

I'm trying to implement some custom caching behaviors for image and video components in my app,  but I am unable to actually see the images that I am caching from the server when i try to use the local copy.  I'm using `rn-fetch-blob` v 0.10.13 and react-native version 0.56.0

my function for checking the cache and either supplying local copy or downloading then supplying local copy is as follows: 
```        
        if (this.state.url !== this.props.source) {
            this.setState({ url: this.props.source });
            let { filePath, extension } = this.parseAssetURL(this.props.source);
            let fileLocation = dirs.CacheDir + '/assetCache/' + filePath;
            console.log('component does not have source in state, or URL has changed checking cache');
            RNFetchBlob.fs.exists(fileLocation)
            .then((exist) => {
                if (exist) {
                    console.log('file already in cache, serving local copy found at ', fileLocation);
                    this.setState({ cachedURI: fileLocation });
                } else {
                    console.log('file not in cache, retrieving from server');
                    RNFetchBlob
                    .config({
                        path: fileLocation
                    })
                    .fetch('GET', this.props.source)
                    .then((res) => {
                        this.setState({ cachedURI: res.path() });
                        console.log("cached file saved to ", res.path())
                    }).catch((err) => {
                        console.log('error', err);
                    })
                }
            })
        }
```
and referencing it in the `<Image>` component I have tried both `source={uri: this.state.cachedURI}` and adding "file://" to the beginning of the path but neither displays the cached images.  The images are being downloaded because I can access them via cli and see them there but when supplied to the component they don't display.

Also of note is that if I do not specify path, but instead use 
```
cacheImage: true,
appendExt: {extension}
```
it does work and displays the images properly.

Help! :) 

and thanks, this is an awesome library!

**Comment by ashmortar** [comment]
Turns out the issue was a % in the filepath i was dynamically creating from the remote uri, once that was changed everything worked super well!

**Comment by abhi-nahi** [comment]
I'm facing the same problem but didn't get your described solution. I am using this for ios application.
Can you please describe it once again...
