### ISSUE TITLE
actionViewIntent error "Failed to find configured root that contains.."

### ISSUE THREAD

**Issue by demarchisd** [joltup/rn-fetch-blob#185]
Versions:
react-native-cli: 2.0.1
react-native: 0.55.1
rn-fetch-blob: 0.10.13,

Hey! I'm having some problems trying to use the `RNFetchBlob.android.actionViewIntent` function. When I call it, it throws me this error:

```
Error: Failed to find configured root that contains /data/data/com.irpfvisaoapp/files/declaration-files/6becc170-b03a-11e8-a70e-876c3834b6e5_2013_DEC.pdf
    at createErrorFromErrorData (NativeModules.js:121)
    at NativeModules.js:78
    at MessageQueue.__invokeCallback (MessageQueue.js:398)
    at MessageQueue.js:137
    at MessageQueue.__guardSafe (MessageQueue.js:314)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:136)
    at debuggerWorker.js: 
```

I'm invoking it like this: `await RNFetchBlob.android.actionViewIntent(path, "application/pdf")`

I'm checking if the file exists before running it using `RNFetchBlob.fs.exists(path)` and it returns `true` as the file really exists. I've also tried to put `file://` in the beginning of the path, but it didn't work either.

```js
const exists = await RNFetchBlob.fs.exists(path)
console.log(path, exists) // "/data/user/0/com.irpfvisaoapp/files/declaration-files/6becc170-b03a-11e8-a70e-876c3834b6e5_2013_DEC.pdf" true
```

I've noticed that the "data" is duplicated in the path inside the error message, but if I try to remove it from the path, the error still occurs.

Any suggestions?

**Comment by antofa** [comment]
I have this problem too.

**Comment by demarchisd** [comment]
Ping... can anybody help with this?

**Comment by demarchisd** [comment]
So, after some research I've found that it's required to [create a provider for it to work](https://developer.android.com/reference/android/support/v4/content/FileProvider).

In the case of rn-fetch-blob, it looks for a provider named `provider_paths` instead of `file_paths`.

So, what I did was to create a xml file `android/app/src/main/res/xml/provider_paths.xml` with the following content:

```xml
<paths xmlns:android="http://schemas.android.com/apk/res/android">              
   <root-path name="root" path="." />                                            
</paths>     
```
Hope this can help people that may have the same problem. C/C @antofa

**Comment by crup** [comment]
This worked for me as well. Though I am unable to open file passed to actionViewIntent when I click on Gallery icon. 
> ```
> <paths xmlns:android="http://schemas.android.com/apk/res/android">              
>    <root-path name="root" path="." />                                            
> </paths>     
> ```

**Comment by bockc** [comment]
@crup did you find a way to fix it ? I noticed the files are saved in `.bin` no matter what I try

**Comment by souzasmatheus** [comment]
@bockc setting it in the config object that gets passed to `RNFetchBloc.config` function fixed it for me:
```
    const config: RNFetchBlobConfig = {
      fileCache: true,
      addAndroidDownloads: {
        useDownloadManager: true,
        notification: true,
        mime: isPdf ? 'application/pdf' : 'image/jpeg',
      },
    };
```
