### ISSUE TITLE
The SDK Build Tools revision (23.0.1) is too low for project ':react-native-fetch-blob'. Minimum required is 25.0.0

### ISSUE THREAD

**Issue by Ronalses** [joltup/rn-fetch-blob#19]
Hi! 
i would like to report this problem and  ans know how solve it.
  

> "dependencies": {
>     "expo": "^25.0.0",
>     "react": "16.2.0",
>     "react-native": "https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz",
>     "react-native-fetch-blob": "^0.10.8",
>     "humps": "^2.0.1",
>     "react-native-image-preview": "^0.3.1",
>     "react-native-keyboard-aware-scroll-view": "^0.4.1",
>     "react-native-modal-datetime-picker": "^4.13.0",
>     "react-native-modal-selector": "^0.0.21",
>     "react-navigation": "^1.0.0-beta.19",
>     "react-redux": "^5.0.6",
>     "redux": "^3.7.2",
>     "redux-logic": "^0.12.3",
>     "redux-persist": "^5.4.0"
>   }

when I execute my project it gives this error.

> * What went wrong:
> A problem occurred configuring project ':app'.
> > Could not resolve all dependencies for configuration ':app:_devRemoteKernelDebugApk'.
>    > A problem occurred configuring project ':react-native-fetch-blob'.
>       > The SDK Build Tools revision (23.0.1) is too low for project ':react-native-fetch-blob'. Minimum required is 25.0.0

> compileSdkVersion 25
> buildToolsVersion "25.0.0"

and i get this error.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fetch-blob:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Thank you very much in advance.

**Comment by tombailey** [comment]
@Ronalses open your project in Android studio and edit the build.gradle which belongs to RNFetchBlob. You will want to change the buildToolsVersion to 25.0.0 there too.

**Comment by echo8795** [comment]
That can be done, but is there some issue why buildToolsVersion isn't being revised in the library itself to keep up with the current RN versions? I am not android dev so i dont know all the impacts of updating the version directly.

**Comment by mikehardy** [comment]
#129 is merged and fixes this, an npm install joltup/rn-fetch-blob to get the github master version I think

**Comment by Traviskn** [comment]
we've just published v0.10.13 which includes the fix from #129
