### ISSUE TITLE
[android] cannot display pdf (temp.pdf cannot be opened)

### ISSUE THREAD

**Issue by pavermakov** [joltup/rn-fetch-blob#193]
- react: 16.0.0
 - react-native: 0.51.0
 - rn-fetch-blob: 0.10.13

Recently I've upgraded my android sdk from 22 to 26. I've noticed that after fetching pdf and attempting to open it, I've receive a toast with the message in the title of this issue. Back on sdk 22 I've used react-native-fetch-blob and everything worked fine.

I use the following method for reading the file:
`RNFB.android.actionViewIntent("/storage/emulated/0/Download/temp.pdf", "application/pdf")`

Has anyone encountered the same issue?

**Comment by ankha0109** [comment]
Have you resolved this problem?

**Comment by ankha0109** [comment]
Have you resolved this issue?

**Comment by pavermakov** [comment]
@ankha0109 Yes, starting from sdk version 26 I had to ask permissions for storage prior to using it.

**Comment by ankha0109** [comment]
@pavermakov Thank you for the information.

**Comment by gauravroy1995** [comment]
but when i try to open, it doesnt open , and i have my permissions accepetd by using permissionsandroid.request
