### ISSUE TITLE
remove or advise on WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by scisci** [joltup/rn-fetch-blob#216]
As of sdk version 19 WRITE_EXTERNAL_STORAGE isn't a required permission and causes additional warnings to show up on our app page. Is it possible to remove this from the manifest in this lib or suggest how we can remove it?

**Comment by Drakoun** [comment]
@scisci Does this link can help you ?
https://facebook.github.io/react-native/docs/removing-default-permissions

**Comment by scisci** [comment]
Yes thanks, I didn't realize React Native itself added these as well.
