### ISSUE TITLE
Unable to show and  save the remote image after caching it in my local machine(iOS)

### ISSUE THREAD

**Issue by nihp** [joltup/rn-fetch-blob#218]
I am using rn-fetch-blob to save the remote url (images).

I have used[https://github.com/joltup/rn-fetch-blob#download-to-storage-directly]( https://github.com/joltup/rn-fetch-blob#download-to-storage-directly) to store the image in my local path and then show it in simulator screen and save that image.

Initially it works fine and I can able to save the image. But now it not showing the image and also I am facing the issue as "Failed to create request body"

Cached image is in the path /Users/XXXXXXXX/Library/Developer/CoreSimulator/Devices/CA18D470-E58C-C2D44C8C9B6A/data/Containers/Data/Application/2FE19E7F-7941-48BC-9344-DE27E78E1AA1/Documents/RNFetchBlob_tmp/RNFetchBlobTmp_5438ceg671xvpnzexlrodb.jpg

Here I have added appendExt to show the image. 

It's so weird for me. Kindly clarify if any one have solution for this.

**Comment by nihp** [comment]
I got solution for this. Solved the error by integrating the react-native-fs package.

**Comment by xstable** [comment]
@nihp can you please explain a bit more what exactly you've done?

**Comment by nihp** [comment]
@xstable I have downloaded the remote image url and then saved to the local path using react-native-fs.

Install react-native-fs package

```
const RNFS = require('react-native-fs');
const shorthash = require("shorthash");

renderImagePath() {
     const name = shorthash.unique(selectedImageUrl);
     const extension = (Platform.OS === 'android')? 'file://': ''
     const path = `${extension}${RNFS.CachesDirectoryPath}/${name}.png`; //U can use any format png, jpeg, jpg

     RNFS.exists(path).then(exists => {
         RNFS.downloadFile({fromUrl:selectedImageUrl, toFile: path}).promise.then(res =>
            {uri: path})
         ).catch(error => {
           console.warn(error);
         });
   }
```

https://github.com/itinance/react-native-fs
