### ISSUE TITLE
RNFetchBlob request error: url == nullnull

### ISSUE THREAD

**Issue by Evangelione** [joltup/rn-fetch-blob#228]
"react": "16.6.0-alpha.8af6728",
"react-native": "0.57.3",
"rn-fetch-blob": "^0.10.13",

    let body = [{
        name: 'image',
        data: RNFetchBlob.wrap(image.path),
      }]
    RNFetchBlob.fetch('POST', 'web.fanhua.com/app/select/upload-imgs',{
       'Content-Type': 'multipart/form-data',
      },body).progress((received, total) => {
        let perent = received / total
        console.log(perent)
      }).then((response) => response.json()).then((response) => {
        console.log(response)
      }).catch((error) => {
        console.log(error)
      })

i got error RNFetchBlob request error: url == nullnull

**Comment by Evangelione** [comment]
help

**Comment by nanaSmile** [comment]
how to solve this problem.I got the same error

**Comment by SteFF1997** [comment]
I have the same error when internet is disconnected

**Comment by lucas-dolsan** [comment]
@Evangelione have you managed to fix it? If you did, please share your solution

**Comment by GavinThomas1192** [comment]
Same problem after upgrading rn to latest version.

**Comment by ramonvermeulen** [comment]
Still having this issue, any recent updates/discoveries?

**Comment by ashokkumar88** [comment]
Any solution?

**Comment by dmitryvko83** [comment]
Any updates please?

**Comment by farzanm14** [comment]
I have the same error, how can I fix it?
why nobody can't fix it?

**Comment by raphaelluiz128** [comment]
Hello, it's a generaly problem with many plugins or packages of React Native. Someone helpe

**Comment by chiefchief** [comment]
why this issue closed with no answer?

**Comment by nivas412** [comment]
Having the same issue solution please..!

**Comment by waqaramjad** [comment]
same issue

**Comment by mtalhagaoglu** [comment]
do we have a solution for that?

**Comment by GabrielDvt** [comment]
Solutions?

**Comment by mtahir08** [comment]
Any solution??. Still getting this error while trying to fetch local image on android

**Comment by FairWageFreelancing** [comment]
bump. Someone provide a fix.

**Comment by babyrusa** [comment]
same issue :( all the threads asked about this never got an answer sadly

**Comment by zeeshan006** [comment]
Error: RNFetchBlob request error: url == nullnull
Anyone have a solution of this problem?

**Comment by stashayancho** [comment]
This error message is misleading -- it seems to happen whenever rn-fetch-blob can't parse the url properly (not necessarily that the url is null). In my case this error was happening when the url didn't start with the URI scheme, so it seems that rn-fetch-blob requires a URI scheme in order to parse the url correctly. When I added `https://`, it started working.

**Comment by nabzmohd** [comment]
check your url is ""
