### ISSUE TITLE
Plugin's android:authorities collide with other plugins, leading to app crash

### ISSUE THREAD

**Issue by mauron85** [joltup/rn-fetch-blob#231]
Hi there, I'm maintainer of https://github.com/mauron85/react-native-background-geolocation.

I'm not here to report bug, but maybe raise awareness about the interesting issue, I was working lately.

I've got reported following issue https://github.com/mauron85/react-native-background-geolocation/issues/320. And it didn't make sense to me at all. After some investigation with issue author we find out that the root cause of the problem is incompatibility between this and my plugin.

The problem is that both plugins are using same `android:authorities:"${applicationId}.provider"`. 
However authorities [must be unique for every content provider](https://stackoverflow.com/a/11977428/3896616). So when both plugins manifests are merged in build step, we've got undefined behaviour, usually leading to crash (as android content provider resolver is confused how to resolve content providers). More details in the linked issue.

So maybe it's good idea for any plugin using content providers to prefix it's android:authorities. That's all I wanted to say. :) Good luck with your plugin.

**Comment by 1uokun** [comment]
same as this issue and here is our [back up plan](https://github.com/lucasferreira/react-native-send-intent/issues/83)
