### ISSUE TITLE
how to avoid getting .ds_store file 

### ISSUE THREAD

**Issue by ZeroCool00** [joltup/rn-fetch-blob#248]
when i m fetching list of files from folder, if folder is empty, than i m getting this file. how to avoid this.

.ds_store is not visible bydefault, its hidden file, but i m getting in response. so how do i avoid it.

**Comment by ZeroCool00** [comment]
Finally solve it.

```
export const listOfFile = () => (dispatch) => {
    let dirs = RNFetchBlob.fs.dirs;
    RNFetchBlob.fs.ls(dirs.DocumentDir + `/maxasl/`)
    // files will an array contains filenames
    .then((files) => {
		if(!!files) {
			files.splice(files.indexOf(".DS_Store"), 1)
			dispatch({
				type: FETCH_FILES,
				payload: files
			});
		}
		
        
    })
}
```

**Comment by flexbox** [comment]
Hi @ZeroCool00 
Can you close the issue to help the maintainers of the lib? 🙏
