### ISSUE TITLE
Tried to access a JS module before the React instance was fully set up

### ISSUE THREAD

**Issue by fgeorgsson** [joltup/rn-fetch-blob#26]
* please provide the version of installed library and RN project.

react-native-fetch-blob@0.10.8 through react-native-cached-image@1.4.0.
react-native@0.47.2

Our app use react-native-cached-image to cache a bunch of images. Some are proloaded early on, when the app is rendered the first time.

Sometimes when the app starts, perhaps after a code-push, we get the error message below logged to Fabric. **The app crashes.**

I am pretty sure it only happens after a code-push is downloaded and the new js-app is restarted, but I'm not sure. It does not happen every time though, seems pretty rare, like 1/100 times a code-push is applied.

(https://github.com/Microsoft/react-native-code-push) 

```
Fatal Exception: java.lang.RuntimeExceptionTried to access a JS module before the React instance was fully set up. Calls to ReactContext#getJSModule should only happen once initialize() has been called on your native module. Raw Text
--
  | com.facebook.react.bridge.ReactContext.getJSModule (ReactContext.java:105)
  | com.RNFetchBlob.RNFetchBlobReq.emitStateEvent (RNFetchBlobReq.java:627)
  | com.RNFetchBlob.RNFetchBlobReq.done (RNFetchBlobReq.java:455)
  | com.RNFetchBlob.RNFetchBlobReq.access$100 (RNFetchBlobReq.java:60)
  | com.RNFetchBlob.RNFetchBlobReq$3.onResponse (RNFetchBlobReq.java:423)
  | okhttp3.RealCall$AsyncCall.execute (RealCall.java:135)
  | okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
  | java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  | java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  | java.lang.Thread.run (Thread.java:776)
```

Any ideas?

**Comment by ghsdh3409** [comment]
@pcguru Did you resolve this issue?

**Comment by The0racle** [comment]
I'm having the same issue. Did anyone find a fix for this?

**Comment by pcguru** [comment]
We've moved to https://www.npmjs.com/package/react-native-fast-image, no longer using rn-fetch-blob.

Did not find any solution all the way up to React Native 0.57 and about 50% of app crashes were related to rn-fetch-blob.

**Comment by rahamin1** [comment]
Did anybody find a fix?
I am using version 0.12.0 and RN 0.62.2.

The error occurs only when I restart the app programmatically (using react-native-restart).
