### ISSUE TITLE
Could not resolve all files for configuration ':rn-fetch-blob:classpath'

### ISSUE THREAD

**Issue by builtbyproxy** [joltup/rn-fetch-blob#261]
Hello

If you are getting the issue 
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':rn-fetch-blob'.
> Could not resolve all files for configuration ':rn-fetch-blob:classpath'.
   > Could not find com.android.tools.build:gradle:2.2.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.jar
     Required by:
         project :rn-fetch-blob
```

Essentially it is trying to pull its classpath from: https://jcenter.bintray.com/com/android/tools/build/gradle/2.2.3/gradle-2.2.3.pom

However if you navigate there it skips from `2.1.3` to `2.3.0`
Therefore, the solution is to change line 16 in `node_modules/rn-fetch-blob/android/build.gradle` to be: `classpath 'com.android.tools.build:gradle:2.2.3'`

--------------------------
**Your buildscript should now be:**

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
    }
}
```

**Comment by mjm918** [comment]
I wasted my 1.5 days for this and able to fixed just now. I assume, you are using gradle 4.x.x and build:gradle version is 3.x.x. If so, then you have the same problem as mine. Open `rn-fetch-blob `project from `node_modules` in android studio. Change the gradle version in `gradle/wrapper/gradle-wrapper.properties` to this `distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip` . after this, go to the rn-fetch-blob build.gradle file and change the classpath same as yours. In my case, `classpath 'com.android.tools.build:gradle:3.1.2'`. Try to sync with gradle. If it shows an error for apply plugin, ignore that. Now try to run your project, should be fine.

There are some other libraries can cause the same problem. In this case, you can run the following command to see which libraries has the same issue:
`./gradlew -q dependencies app:dependencies --configuration debugAndroidTestCompileClasspath`

In my case, realmjs and rn-fetch-blob had this issue. 
I created a PR here:
https://github.com/joltup/rn-fetch-blob/pull/262

**Comment by rodalmeida** [comment]
you can find a solution on https://github.com/joltup/rn-fetch-blob/issues/257

**Comment by Krosh** [comment]
@builtbyproxy for me it doesn't work without adding google() in repository

**Comment by vforvasile** [comment]
it seems that a lot of Google repos were down yesterday [https://issuetracker.google.com/issues/120759347](url)

**Comment by tomaskallup** [comment]
So there is no way to build app with gradle build tools 3+?

**Comment by builtbyproxy** [comment]
haha @rodalmeida that is a horribly generic issue title, no wonder I couldnt find it 
Thanks for the link though

This fix could be specific to my project setup it seems, thanks for everyone's input
