### ISSUE TITLE
RNFetchBlob request timed out error without network connection

### ISSUE THREAD

**Issue by GabeConsalter** [joltup/rn-fetch-blob#270]
My app makes requests with RNFetchBlob and works fine. But when device is not connected, after timeout, my app returns an error:

![simulator screen shot - iphone 6s - 2018-12-28 at 11 03 19](https://user-images.githubusercontent.com/6640360/50516288-14fa6280-0a91-11e9-8e51-77970eff38b0.png)

I can get error on `.catch()` method but I need an alternative to not show the error and not crash my app.
My request:
```
return await RNFetchBlob
  .config({ timeout: 7000 })
  .fetch('GET', 'https://...', {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'Cookie': 'PHPSESSID=api'
    }
  )
  .then((res) => res.json())
  .then((data) => {
    return data;

  }).catch((err) => {
    console.log('ERROR', err);

  }
);
```

**Comment by Udbhav12** [comment]
What is the default timeout ? You have mentioned 7000 ms in your sample code above
