### ISSUE TITLE
Cannot ready property DocumentDir of undefined

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [joltup/rn-fetch-blob#285]
"rn-fetch-blob": "^0.10.15"
"react-native": "0.56.0",

1. install de lib via yarn
2. react-native link rn-fetch-blob
3. add android permissions

when I add the import line (import RNFetchBlob from 'rn-fetch-blob') the error appears, just it, cant do anything else (i dont even need to be on the screen where I imported, it will crash anyway)
im testing on iOS simulator btw

![image](https://user-images.githubusercontent.com/29608698/51341281-1efff780-1a78-11e9-9a4d-9abd8e121756.png)

**Comment by Priyatham51** [comment]
Same issue here

**Comment by Priyatham51** [comment]
@diego-lipinski-de-castro  I think we both missed adding the required pod file for ios
Please add the following link 
`pod 'rn-fetch-blob',  :path => '../node_modules/rn-fetch-blob'`

Then do a `pod install`

**Comment by diego-lipinski-de-castro** [comment]
I have no pod file, I tried to do a pod init, added your line, but then pod install fails with lots of errors

![image](https://user-images.githubusercontent.com/29608698/51386011-1c4ce300-1b08-11e9-8a71-afe1e10cb9c3.png)

**Comment by diego-lipinski-de-castro** [comment]
Not sure if i should just update everything or what

**Comment by diego-lipinski-de-castro** [comment]
Ok i got it, the problem is that i used yarn, npm does some post install bs, i didnt used pod @Priyatham51, as so, its very important to use npm instead of yarn

**Comment by pengcao1** [comment]
I have same issue with `npm install`

**Comment by hexatex** [comment]
> I have same issue with `npm install`

Me too :'(

**Comment by scottyantipa** [comment]
You probably need to manually link: https://github.com/joltup/rn-fetch-blob/wiki/Manually-Link-Package#index

**Comment by nitishlovesandroid** [comment]
still the error not resolved
