### ISSUE TITLE
Android RNFetchBlob.fetch doesn't decode response body as utf8, sometimes

### ISSUE THREAD

**Issue by aarondail** [joltup/rn-fetch-blob#297]
We are using rn-fetch-blob to do all networking in our app, and are running into an issue on Android where sometimes JSON returned from our server is not properly decoded by rn-fetch-blob.  Basically, Chinese, Japanese, and other non-ASCII characters get all messed up in the response object that is sent to our javascript code.  It is still "valid" JSON, and all ascii characters are fine, but the non-ASCII characters are messed up. 

Basically a response from the server that should look like this:

```
{ "name": "Chinese - 让教师及学生更为有效地操作" }
```

Is getting returned to us from rn-fetch-blob as this:
```
{ "name": "Chinese - è®©æå¸åå­¦çæ´ä¸ºææå°æä½" }
```

Sometimes!  This is important to note.  Lots of non-ASCII text does seem to be fine and rn-fetch-blob behaves as expected.  I am not 100% sure what characters cause the problem to manifest, but I am sure I know where the problem is after debugging rn-fetch-blob and have a good idea of what the fix might be.

The problem is this line:
https://github.com/joltup/rn-fetch-blob/blob/master/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java#L512

That line is taking the bytes of the response body and _encoding_ them into utf8.  *Sometimes* it throws a `CharacterCodingException` and then the `catch` body sends the bytes through some kind of base 64 encoding which I dont understand but basically sends the JSON back to the app without decoding it from utf8.  Thus, the problem.

We can remove that line, and everything is ok.  That is one possible fix.

However, I think what the code wants to be doing is _decoding_ the bytes FROM utf8 (not encoding them INTO utf8, because the response body is _already_ in utf8).

I could be totally off base here.  But if I replace that line with:
`Charset.forName("UTF-8").newDecoder().decode(ByteBuffer.wrap(b));`

Everything works ok and I feel like that probably honors the intention of the code.

(I also think this is what react-native is doing, though also to be honest I dont understand the flow of their networking code well: https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/ReactAndroid/src/main/java/com/facebook/react/modules/network/ProgressiveStringDecoder.java#L67)

Anyways, I am happy to submit a PR if one of those things sounds like an appropriate fix, just let me know.

* RN 0.57.1
* rn-fetch-blob 0.10.13

**Comment by YoshiteruIwasaki** [comment]
The same thing happened to me. 
Like this text.

```
(๑•̀ㅂ•́)و✧

(๑˃̵ᴗ˂̵)و
```

 I set "RNFB-Response" to utf8.
https://github.com/joltup/rn-fetch-blob/wiki/Fetch-API#rnfb-response-base64--utf8

````
'RNFB-Response': 'utf8',
````

But this setting cause return blank text.


https://github.com/joltup/rn-fetch-blob/blob/master/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java#L522


```
callback.invoke(null, RNFetchBlobConst.RNFB_RESPONSE_UTF8, "");
```

So, I fixed like this.


```
callback.invoke(null, RNFetchBlobConst.RNFB_RESPONSE_UTF8, new String(b));
```

**Comment by mo-ah-dawood** [comment]
happened to me with arabic

**Comment by alainib** [comment]
> 
> 
> happened to me with arabic

hello. same problem, how did you solve it ?

**Comment by yasir-netlinks** [comment]
Hi there, I am facing this problem with the latest release ? How can I fix it ?

**Comment by mskarimi** [comment]
> We are using rn-fetch-blob to do all networking in our app, and are running into an issue on Android where sometimes JSON returned from our server is not properly decoded by rn-fetch-blob. Basically, Chinese, Japanese, and other non-ASCII characters get all messed up in the response object that is sent to our javascript code. It is still "valid" JSON, and all ascii characters are fine, but the non-ASCII characters are messed up.
> 
> Basically a response from the server that should look like this:
> 
> ```
> { "name": "Chinese - 让教师及学生更为有效地操作" }
> ```
> 
> Is getting returned to us from rn-fetch-blob as this:
> 
> ```
> { "name": "Chinese - è®©æ��å¸�å��å­¦ç��æ�´ä¸ºæ��æ��å�°æ��ä½�" }
> ```
> 
> Sometimes! This is important to note. Lots of non-ASCII text does seem to be fine and rn-fetch-blob behaves as expected. I am not 100% sure what characters cause the problem to manifest, but I am sure I know where the problem is after debugging rn-fetch-blob and have a good idea of what the fix might be.
> 
> The problem is this line:
> https://github.com/joltup/rn-fetch-blob/blob/master/android/src/main/java/com/RNFetchBlob/RNFetchBlobReq.java#L512
> 
> That line is taking the bytes of the response body and _encoding_ them into utf8. _Sometimes_ it throws a `CharacterCodingException` and then the `catch` body sends the bytes through some kind of base 64 encoding which I dont understand but basically sends the JSON back to the app without decoding it from utf8. Thus, the problem.
> 
> We can remove that line, and everything is ok. That is one possible fix.
> 
> However, I think what the code wants to be doing is _decoding_ the bytes FROM utf8 (not encoding them INTO utf8, because the response body is _already_ in utf8).
> 
> I could be totally off base here. But if I replace that line with:
> `Charset.forName("UTF-8").newDecoder().decode(ByteBuffer.wrap(b));`
> 
> Everything works ok and I feel like that probably honors the intention of the code.
> 
> (I also think this is what react-native is doing, though also to be honest I dont understand the flow of their networking code well: https://github.com/facebook/react-native/blob/1151c096dab17e5d9a6ac05b61aacecd4305f3db/ReactAndroid/src/main/java/com/facebook/react/modules/network/ProgressiveStringDecoder.java#L67)
> 
> Anyways, I am happy to submit a PR if one of those things sounds like an appropriate fix, just let me know.
> 
> * RN 0.57.1
> * rn-fetch-blob 0.10.13

Your solution worked for me
Thanks

**Comment by sejeeth11** [comment]
Try below code i resolved this Error for arabic  
  
  // This usually mean the data is contains invalid unicode characters but still valid data,
                        // it's binary data, so send it as a normal string
                        catch(CharacterCodingException ignored) {
                            
                          //  if(responseFormat == ResponseFormat.UTF8) {
                                String utf8 = new String(b);
                                callback.invoke(null, RNFetchBlobConst.RNFB_RESPONSE_UTF8, utf8);
                            // }
                            // else {
                            //     //callback.invoke(null, RNFetchBlobConst.RNFB_RESPONSE_BASE64, android.util.Base64.encodeToString(b, Base64.NO_WRAP));
                            // }
