### ISSUE TITLE
[Android][DownloadManager] Unsupported path DocumentDir

### ISSUE THREAD

**Issue by nyunyu95** [joltup/rn-fetch-blob#304]
Hi,

It appears that it is impossible to download a file to DocumentDir location. I'm getting an error of type "Unsupported path /data/data/[package]/file/..."

If I do not use the DownloadManager everything works fine.

![image](https://user-images.githubusercontent.com/1191641/52492740-1f4c6800-2bca-11e9-8e7e-c0e58bb7c672.png)

The config object I'm using before fetching : 
```
config = {
        addAndroidDownloads: {
          useDownloadManager: true,
          notification: true,
          path:  RNFetchBlob.fs.dirs.DocumentDir + '/titi.mp4',
          mime: 'video/mp4'
        }
      }
```
Any ideas ? Thanks !

**Comment by wincjh** [comment]
RNFetchBlob.fs.dirs.DownloadDir is for Android. DocumentDir is for ios i think

**Comment by Rafay3198** [comment]
I got the same problem

**Comment by Baterka** [comment]
Not working on Android 10 with `dirs.DownloadDir`

**Comment by Sheharyar566** [comment]
Still ain't working

**Comment by syedibrahimt** [comment]
Any updates on this issue?

**Comment by Manngold** [comment]
i solve this issue using folder check add this folder check and access permission
```
import {PermissionsAndroid} from 'react-native';
const folderValidCheck = async () => {
  try {
    // add read, write permissions
    await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
    );
    await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
    );

    const folder = await RNFetchBlob.fs.exists(RNFetchBlob.fs.dirs.DownloadDir); //check Download directory check
    if (!folder) {
      //code download logic
    }
  } catch (error) {
    console.log(error);
  }
}
```

**Comment by redefinered** [comment]
@Manngold hi. would you mind if I take a peek at your RNFetchBlob.config configuration? Thanks!

**Comment by Kolosafo** [comment]
Use `RNFetchBlob.fs.dirs.DCIMDir` for path not `...dirs.DocumentDir `

**Comment by DePavlenko** [comment]
Having the same issue but with `RNFetchBlob.fs.dirs.CacheDir`

**Comment by eliasg52** [comment]
> Having the same issue but with `RNFetchBlob.fs.dirs.CacheDir`

I have the same issue, were you able to resolve it?

**Comment by DePavlenko** [comment]
> > Having the same issue but with `RNFetchBlob.fs.dirs.CacheDir`
> 
> I have the same issue, were you able to resolve it?

Nope, I just removed "addAndroidDownloads" from "RNFetchBlob.config" completely
