### ISSUE TITLE
Cannot read property 'DocumentDir' of undefined

### ISSUE THREAD

**Issue by justinformentin** [joltup/rn-fetch-blob#320]
I'm using expo 32, I wish I could add more details, but I can't even import the package. 

Anywhere I try to import it, I get:

Cannot read property 'DocumentDir' of undefined

Is it because I'm using expo?

**Comment by luizzenha** [comment]
Hey Justin,

I'm not using expo, and i had this same problem.
To solve it you must add "**libRNFetchBlob.a**" at **Linked Frameworks and Libraries**

**Comment by justinformentin** [comment]
Thank you you so much!

**Comment by TheoGit** [comment]
@luizzenha I'm not finding "libRNFetchBlob.a" - installed "react-native-fetch-blob" 0.10.3, any suggestions

**Comment by scottyantipa** [comment]
You probably need to manually link: https://github.com/joltup/rn-fetch-blob/wiki/Manually-Link-Package#index
