### ISSUE TITLE
undefined is not an object (evaluating RNFetchBlob.DocumentDir)

### ISSUE THREAD

**Issue by mschipperheyn** [joltup/rn-fetch-blob#329]
RN Fetch blob: 0.10.15
React-native: 0.57.8
I don't use Cocoa pods
Other native libs in use: react-native-vector-icons, react-native-image-crop-picker, react-native-fs, react-native-config, react-native-photo-view, react-native-material-kit, react-native-image-picker, react-native-fast-image, react-native-lineair-gradient

I've spent a day trying to get passed this problem. It occurs on both Android and XCode. Tried everything I found on this issue, hard cleans, restarts, etc. I'm pretty sure all the install steps were followed correctly and verified that various times. In fact, it worked correctly for a long time.

A few things I noticed that make me wonder:

- when I do a react-native link rn-fetch-blob, on XCode a recovered reference is installed for rn-fetch-blob and I see two different ids in the project file being defined. Tried react-native unlink rn-fetch-blob, uninstall, rm -rf node_modules, reinstall

- On Android, where I'm a bit more at home debugging, the method `getSystemfolders`, that defines the DocumentDir is never called, even though as far as I can tell, it should be.

I hope this context helps someone make a brilliant suggestion.

**Comment by mschipperheyn** [comment]
This is resolved. Our issue was that we implemented `react-native-web` and aliased react-native-web in babel in stead of webpack.

**Comment by mo-patel** [comment]
@mschipperheyn I also have the same issue having `react-native-web`. Can i please ask exactly what you did to resolve it?
