### ISSUE TITLE
File system operations on IOS fail with file:// uris

### ISSUE THREAD

**Issue by cristianoccazinsp** [joltup/rn-fetch-blob#343]
"rn-fetch-blob": "0.10.15",
"react": "16.8.6",
"react-native": "0.59.4"

Hello,

Looks like trying to call RNFetchBlob.fs.exists, readFile, unlink, etc., will fail if the file path contains "file://" on IOS. Oddly, it works on Android just fine.

Removing file:// from the calls is definitely not an option (happens in way too many places). Storing the file path without it is also not an option, since the file:// part is also needed for other things.

Is there a way to monkey patch RNFetchBlob.fs.* to just do that file:// removal if it's running on iOS? Should the library just do it by itself internally?

**Comment by alpha0010** [comment]
Not certain about intended functionality, but you could [patch in](https://github.com/ds300/patch-package) a helper similar to [`asset()`](https://github.com/joltup/rn-fetch-blob/blob/master/fs.js#L50) and use it to wrap all path usages in `fs.js`.

**Comment by crobinson42** [comment]
Duplicate: #194 

@cristianoccazinsp please close this issue.
