### ISSUE TITLE
download error on some devices

### ISSUE THREAD

**Issue by Jeijie** [joltup/rn-fetch-blob#348]
an error occured:
![image](https://user-images.githubusercontent.com/9338052/56573726-4aa0f980-65f4-11e9-80f2-75890945beba.png)

### 
React Native Environment Info:
  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 8.12 GB / 15.88 GB
  Binaries:
    Node: 8.12.0 - F:\install\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Users\GDYT\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - F:\install\nodejs\npm.CMD

### my code:

      RNFetchBlob.config({
        addAndroidDownloads: {
          useDownloadManager: true,
          title: "xxxx.apk",
          description: "xxxx",
          mime: "application/vnd.android.package-archive",
          mediaScannable: true,
          notification: true,
          path: RNFetchBlob.fs.dirs.DownloadDir + "/xxxx-" + version + ".apk"
        }
      })
        .fetch("GET", xxxxxxxx)
        .then(res => {
          android.actionViewIntent(
            res.path(),
            "application/vnd.android.package-archive"
          );
        })

**Comment by huytran123** [comment]
@Jeijie You can check your file in DownloadDir folder. if it is exist and downloaded success. Please you can follow me to fix it. I have same issue on Mi A1( Android 9).
1. Go to RNFetchBlob class in "node_modules\rn-fetch-blob\android\src\main\java\com\RNFetchBlob\RNFetchBlob.java"
2. Find method "actionViewIntent"
3. Replace "intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);"=>"intent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_ACTIVITY_NEW_TASK);"

4. Add " <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>" to your "AndroidManifest.xml" app.

**Comment by gbferreira** [comment]
Same problem and this fixed. I suggest you revise the name of issue.

**Comment by huytran123** [comment]
@gbferreira current version 0.10.15 not fixed this issue, why do you closed it? i think they fixe it and update version and then close this issue
