### ISSUE TITLE
Invoke would be called more than once during cp call

### ISSUE THREAD

**Issue by thiszhong** [joltup/rn-fetch-blob#35]
RNFetchBlob version: 0.10.8
The code raises a java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code. when cp errors but successfully closes its streams.
That is already existed in the old repository and had a PR: [https://github.com/wkh237/react-native-fetch-blob/pull/408](https://github.com/wkh237/react-native-fetch-blob/pull/408)
But now it is still here.

**Comment by padampadam** [comment]
+1
