### ISSUE TITLE
Can't download file with http domain url in android 9 pie

### ISSUE THREAD

**Issue by ganesh98a** [joltup/rn-fetch-blob#351]
Hi ! i am using rnfetchblob to download the file using get method through HTTP domain url. it's not working in android 9 pie version only. also i have tried and cross check with android behavior changes of version update

here my code
```
const { config, fs } = RNFetchBlob;
 let options = {
        
        addAndroidDownloads: {
          fileCache: true,
          path: PictureDir + '/RFIs' + Math.floor(date.getTime() + date.getSeconds() / 2) + '.pdf',
          useDownloadManager: true,
          notification: true,
          mediaScannable: true,
          path: PictureDir + '/RFIs' + Math.floor(date.getTime() + date.getSeconds() / 2) + '.pdf',
          description: 'Downloading.',
          mime: 'application/pdf'
        }
      };
pdfData='http://...';
config(options).fetch('GET', pdfData).then((res) => {
});
```
Behavior changes are applied
Manifest file *****
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.fulcrum">
 <application 
        xmlns:tools="http://schemas.android.com/tools"
        android:name=".MainApplication"
        android:allowBackup="true"
         android:usesCleartextTraffic="true"
        android:networkSecurityConfig="@xml/network_security_config"
        >
        <uses-library android:name="org.apache.http.legacy" android:required="false"/>
</application>
</manifest>
```
network_security_config.xml*****

```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
```
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
      Memory: 1.39 GB / 7.84 GB
    Binaries:
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  React-native version
     "react": "16.8.3",
      "react-native": "0.59.5"
      "rn-fetch-blob": "^0.10.13"

**Note: it's working with HTTPS domain url with above code & environment setup**

Will you pls get me out to solve this.

Thanks

**Comment by jpodpro** [comment]
it looks like pie disables http traffic by default. there's a manifest setting that appears to allow it. read this for more info:
https://github.com/facebook/react-native/issues/24627

**Comment by mayankgarg056** [comment]
Same problem with me

**Comment by tatva-hiral** [comment]
Same issue facing, android 9 file not downloaded

**Comment by ganesh98a** [comment]
@tatva-hiral @mayankgarg056 Pls look into this it may helps you - https://github.com/joltup/rn-fetch-blob/pull/317

**Comment by tatva-hiral** [comment]
@ganesh98a It's not working on specific devices, that is android 9-oxygen OS(oneplus) or after updating android that shows me Android security patch level for other devices.

**Comment by ganesh98a** [comment]
@tatva-hiral pls make sure you have added those line below.
```
<application
android:usesCleartextTraffic="true"
>
<uses-library android:name="org.apache.http.legacy" android:required="false"/>
```
After adding that. i have run the app and resetarted my mobile. it has worked

**Comment by NSR88** [comment]
@ganesh98a I tried doing the same, but still not working for me on Android Pie (9). What else is missing?
