### ISSUE TITLE
RN 0.60 - Incompatible React/Core dependency in .podspec

### ISSUE THREAD

**Issue by locorider** [joltup/rn-fetch-blob#365]
We encountered a (I guess) minor issue when executing ```pod install```. The required dependency in ```rn-fetch-blob.podspec``` React/Core cannot be found.
React Native 0.60 defines ```React/Core``` as **```React-Core```** in the Podfile.

Renaming ```React/Core``` to **```React-Core```** in ```rn-fetch-blob.podspec``` did the trick for us.

* rn-fetch-blob version: 0.10.15
* react-native version: 0.60.0-rc.0

**Comment by nicoabie** [comment]
Fixed in https://github.com/joltup/rn-fetch-blob/pull/397

**Comment by AliEbrahimpour** [comment]
not update in new version
please check it

**Comment by Traviskn** [comment]
Resolved by #397
