### ISSUE TITLE
how to upload an base64 string image to azure blob

### ISSUE THREAD

**Issue by ManuRodgers** [joltup/rn-fetch-blob#373]
Hi ! Thank you for reporting an issue, but we would like to remind you, we have a trouble shooting page in our wiki. 
You may want to take a look on that page or find issues tagged "trouble shooting" :p 

* please provide the version of installed library and RN project.
* a sample code snippet/repository is very helpful to spotting the problem.
* issues which have been tagged as 'needs feedback', will be closed after 2 weeks if receive no feedbacks.
* issues lack of detailed information will be closed without any feedback

**Comment by nik910** [comment]
const assetPath = `${_trimEnd(sasContainerUri, '/')}/${container}/${uploadPath}`;

  await RNFetchBlob.fetch('PUT', `${assetPath}?${sasToken}`, {
    'x-ms-blob-type': 'BlockBlob',
    'content-type': 'application/octet-stream',
    'x-ms-blob-content-type': file.type,
  }, base64String);

  return assetPath;

**Comment by AnirudhWT** [comment]
worked thank you...

**Comment by votrunghau11** [comment]
> const assetPath = `${_trimEnd(sasContainerUri, '/')}/${container}/${uploadPath}`;
> 
> await RNFetchBlob.fetch('PUT', `${assetPath}?${sasToken}`, {
> 'x-ms-blob-type': 'BlockBlob',
> 'content-type': 'application/octet-stream',
> 'x-ms-blob-content-type': file.type,
> }, base64String);
> 
> return assetPath;

hi @nik910  
i want to upload a video from react native client! 
now i'm stuck with azure blob storage 
can u help me how to upload it with using RNFetchBlob

**Comment by AnirudhWT** [comment]
I have tested to upload the video from my system to the azure storage blob and that was successful.I used postman for testing the scenario and i am sure it will also work in React-native as well.
Enlisted steps i didPUT ={bloburl}/{containername}/{filename}?{sastoken}
headers were:
Content-Type :FileTypex-ms-blob-type:BlockBlob
Content-Length:size in kbs
and in the body i uploaded the video file

**Comment by votrunghau11** [comment]
can you give me an example @AnirudhWT

**Comment by AnirudhWT** [comment]
are you facing issue in uploading or converting the video in base64 ? Since uploading part is clear I think.please address the exact issue.

**Comment by votrunghau11** [comment]
yub bro

i'm stuck right now
i follow your step but when i upload it idont receive any response.
i cant check is it saved in azure storage because i dont have azure account
(company sercurity problems)
so how can i check it ??

and i'm just a newbie
please help me as soon as if you can
this is my code
RNFetchBlob.fetch(fetchConfig, `https://${azureStorageBlob.blobUrl}/${
azureStorageBlob.containerName}/${azureStorageBlob.videoName}?${
azureStorageBlob.sasToken}`, {
'x-ms-blob-type': 'BlockBlob',
'content-type': 'application/octet-stream',
'x-ms-blob-content-type': file.type,
}, RNFetchBlob.wrap(localUri))

Vào Th 2, 23 thg 3, 2020 vào lúc 13:39 AnirudhWT <notifications@github.com>
đã viết:

**Comment by AnirudhWT** [comment]
if you want  to test strictly from react-native then you should have access to the account.. without that you wont be able to confirm  it is uploaded or not. 
or you can also check by listing all the blobs by using the enlisted method.

blobService.listBlobsSegmented('mycontainer', null, function (error, results) {
    if (error) {
        // List blobs error
    } else {
        for (var i = 0, blob; blob = results.entries[i]; i++) {
            // Deal with blob object
        }
    }
});

**Comment by votrunghau11** [comment]
how can i check when alias name of container always change

Vào Th 2, 23 thg 3, 2020 vào lúc 13:56 AnirudhWT <notifications@github.com>
đã viết:

**Comment by votrunghau11** [comment]
if you have any chat channel can you give me ? it's easier to talk with u

Vào Th 2, 23 thg 3, 2020 vào lúc 14:51 Trung Hậu Võ <vth1122@gmail.com>
đã viết:

**Comment by sharadkatre19** [comment]
Can we upload with file URI & custom name to file to azure blob storage? Can you share some sample code? @nik910  I have tried your example but getting the 409 status code. The requested operation is not allowed in the state on the entity.
