### ISSUE TITLE
RNFetchBlob.fs.dirs.DownloadDir is undefined on iOS

### ISSUE THREAD

**Issue by kemicofa** [joltup/rn-fetch-blob#387]
Library 0.10.8

`RNFetchBlob.fs.dirs.DownloadDir` returns undefined on iOS (emulator), but works fine on Android device.

```
const pathToWrite = `${RNFetchBlob.fs.dirs.DownloadDir}/${filename}.csv`;
RNFetchBlob.fs
.writeFile(pathToWrite, data, 'utf8')
.then(() => {
    //success
})
.catch(error => console.log(error);
```

**Comment by Jhonsebas77** [comment]
Hello, try with this
`const { fs } = RNFetchBlob`
`const DownloadDir = isIOS ? fs.dirs['MainBundleDir'] : fs.dirs['SDCardApplicationDir']`
` const pathDownload = "${DownloadDir}/vouchers/${file_name}.pdf"`

**Comment by Traviskn** [comment]
download dir is ios only

**Comment by shahheli06** [comment]
Add in INFO.plist

<key> UIFileSharingEnabled</key>
<true/>
<key>LSSupportsOpeningDocumentsInPlace</key>
<true/>

**Comment by danielkhaleb** [comment]
In IOS you can use RNFetchBlob.fs.dirs.DocumentDir, this solution help me -> https://stackoverflow.com/questions/60052019/rn-fetch-blob-download-docx-or-pdf-from-url-in-ios
