### ISSUE TITLE
How to send the Credentials:"same-origin" to the fetch method for download file 

### ISSUE THREAD

**Issue by gowthamans268** [joltup/rn-fetch-blob#388]
I am using the react native fetch blob and my server is validating for the session cookies, We need to pass the "Credentials:Same-origin" inorder to access the file from the web system. We couldn't find any way to pass this. 

Is there any way to use the existing session in react native fetch blob .? Please suggest.

**Comment by Spisaczek** [comment]
Hey @gowthamans268 ,did you solve the problem? I'm facing the same problem :/

**Comment by gowthamans268** [comment]
Please set trusty: true in RNFetchBlob.config({...})

By default the session cookies will be shared to the server.
