### ISSUE TITLE
`react-native link` hangs when react-native-fetch-blob is a dependency

### ISSUE THREAD

**Issue by blbradley** [joltup/rn-fetch-blob#39]
Hello!

> * please provide the version of installed library and RN project.

react-native-fetch-blob@0.10.8
react-native@0.55.2

I've tried this on both node 6 and 8.

> * a sample code snippet/repository
```
✗ react-native link
Scanning folders for symlinks in /home/brandon/src/DocentReact/node_modules (5ms)
rnpm-install info Platform 'ios' module react-native-background-timer is already linked
rnpm-install info Platform 'android' module react-native-background-timer is already linked
rnpm-install info Platform 'android' module react-native-billing is already linked
rnpm-install info Platform 'ios' module react-native-blur is already linked
rnpm-install info Platform 'android' module react-native-blur is already linked
rnpm-install info Platform 'ios' module react-native-device-info is already linked
rnpm-install info Platform 'android' module react-native-device-info is already linked
RNFetchBlob checking app version ..
RNFetchBlob detected app version => 0.55
Add Android permissions => false
react-native-fetch-blob will not automatically add Android permissions after 0.9.4 please run the following command if you want to add default permissions :

        RNFB_ANDROID_PERMISSIONS=true react-native link

rnpm-install info Platform 'ios' module react-native-fetch-blob is already linked
rnpm-install info Platform 'android' module react-native-fetch-blob is already linked
rnpm-install info Platform 'ios' module react-native-maps is already linked
rnpm-install info Platform 'android' module react-native-maps is already linked
rnpm-install info Platform 'ios' module react-native-sound is already linked
rnpm-install info Platform 'android' module react-native-sound is already linked
rnpm-install info Platform 'ios' module react-native-svg is already linked
rnpm-install info Platform 'android' module react-native-svg is already linked
rnpm-install info Platform 'ios' module react-native-view-overflow is already linked
rnpm-install info Platform 'android' module react-native-view-overflow is already linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project
<--- must press enter here to continue
```

Removing react-native-fetch-blob as a dependency does not produce this behavior.

**Comment by blbradley** [comment]
[Here](https://github.com/blbradley/react-native-fetch-blob-issue-39) is a repository that exhibits the behavior.

**Comment by Ryabchikus** [comment]
i have same error:
"react-native link" crash if rn-fetch-blob module installed:
(full path was `cutted)
`> react-native link
Scanning folders for symlinks in D:\........\xxxxxx\node_modules (50ms)
rnpm-install info Platform 'ios' module react-native-fs is already linked
rnpm-install info Platform 'android' module react-native-fs is already linked
rnpm-install info Platform 'ios' module react-native-i18n is already linked
rnpm-install info Platform 'android' module react-native-i18n is already linked
rnpm-install info Platform 'ios' module react-native-vector-icons is already linked
rnpm-install info Platform 'android' module react-native-vector-icons is already linked
rnpm-install info Platform 'ios' module react-native-version-number is already linked
rnpm-install info Platform 'android' module react-native-version-number is already linked
rnpm-install info Platform 'ios' module react-native-video is already linked
rnpm-install info Platform 'android' module react-native-video is already linked
rnpm-install info Platform 'ios' module react-native-zip-archive is already linked
rnpm-install info Platform 'android' module react-native-zip-archive is already linked
module.js:549
    throw err;
    ^

Error: Cannot find module 'D:\........\xxxxxx\node_modules\react-native-fetch-blob\scripts\prelink.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
D:\........\xxxxxx\node_modules\react-native\local-cli\core\makeCommand.js:27
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node ./node_modules/react-native-fetch-blob/scripts/prelink.js" command
    at ChildProcess.prelink (D:\........\xxxxxx/node_modules/react-native/local-cli/core/makeCommand.js:27:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)`

maybe it's need to rename in several places react-native-fetch-blob -> rn-fetch-blob
sorry my english...

**Comment by blbradley** [comment]
hey @Ryabchikus 

Thanks for the response. This is not the same issue.

**Comment by blbradley** [comment]
I'm going to close this issue. I originally opened it because I thought `react-native link` was required to for a new app build. The issue being fixed in Node 10 should be sufficient.

**Comment by Traviskn** [comment]
@Ryabchikus It seems when I renamed the project to `rn-fetch-blob` I missed several occurrences of `react-native-fetch-blob` in the codebase.  That should be fixed in the newest release just published.  

@blbradley Thanks, sorry I wasn't able to dig into your original issue more, hopefully it won't be an issue for too many others with newer node versions!

**Comment by blbradley** [comment]
No worries. Just wanted to report the issue and the potential workaround for others. It's a less critical issue after I discovered that `react-native link` does not need to be part of a build in a CI process for react-native apps.

Thanks for taking over the project!

**Comment by Ryabchikus** [comment]
@Traviskn
Thanks a lot for fix!
Big problem is gone, now 2 small minor problems:
1) command "react-native link" does not finished:
`> react-native link
Scanning folders for symlinks in D:\......\xxxxxx\node_modules (53ms)
rnpm-install info Platform 'ios' module react-native-fs is already linked
rnpm-install info Platform 'android' module react-native-fs is already linked
rnpm-install info Platform 'ios' module react-native-i18n is already linked
rnpm-install info Platform 'android' module react-native-i18n is already linked
rnpm-install info Platform 'ios' module react-native-vector-icons is already linked
rnpm-install info Platform 'android' module react-native-vector-icons is already linked
rnpm-install info Platform 'ios' module react-native-version-number is already linked
rnpm-install info Platform 'android' module react-native-version-number is already linked
rnpm-install info Platform 'ios' module react-native-video is already linked
rnpm-install info Platform 'android' module react-native-video is already linked
rnpm-install info Platform 'ios' module react-native-zip-archive is already linked
rnpm-install info Platform 'android' module react-native-zip-archive is already linked
RNFetchBlob checking app version ..
RNFetchBlob detected app version => 0.55
Add Android permissions => false
rn-fetch-blob will not automatically add Android permissions after 0.9.4 please run the following command if you want to add default permissions :

        RNFB_ANDROID_PERMISSIONS=true react-native link

rnpm-install info Linking rn-fetch-blob ios dependency
rnpm-install info Platform 'ios' module rn-fetch-blob has been successfully linked
rnpm-install info Linking rn-fetch-blob android dependency
rnpm-install info Platform 'android' module rn-fetch-blob has been successfully linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project`

that's all, it's not return to command line.

2) string "compile project(':rn-fetch-blob')" not adds to "\android\app\build.gradle"
I add it manually and package works.

**Comment by choudharyab** [comment]
i have same issuse

**Comment by nguyen-coding-c** [comment]
Same issue!

**Comment by nguyen-coding-c** [comment]
Fixed on version 10 thanks
