### ISSUE TITLE
AsyncStorage Warning

### ISSUE THREAD

**Issue by Matiassimone** [joltup/rn-fetch-blob#391]
### Warning generated by the AsyncStorage deprecation

Hello, I am creating the next issue to warn that in the new versions of RN, the library of AsyncStorage has been separated, which generates a Warning about the deprecation of AsyncStorage.

* React Native version 0.59

I have created **the following PR to solve this error**, eliminating an unnecessary import in the project code. https://github.com/joltup/rn-fetch-blob/pull/390

**Comment by Traviskn** [comment]
resolved by #354
