### ISSUE TITLE
Unable to get provider com.RNFetchBlob.Utils.FileProvider: java.lang.ClassNotFoundException: Didn't find class "com.RNFetchBlob.Utils.FileProvider"

### ISSUE THREAD

**Issue by OrlandoRomo** [joltup/rn-fetch-blob#404]
Hi, I'm trying to build the android project that react native generates in Android Studio but after build successfully the project and run it in a virtual device, the application stops at the moment when is launched and I got this in the terminal.

![Screen Shot 2019-07-16 at 12 22 23](https://user-images.githubusercontent.com/34588445/61315524-919e2580-a7c4-11e9-888e-7fc701be75a3.png)

My currently environment

react-native: `59.9`
rn-fetch-blob: `0.10.15`

:(

**Comment by arcollector** [comment]
you need to renamed `android.support.v4.content.FileProvider` to `androidx.core.content.FileProvider` and `android.support.annotation.Nullable` to `androidx.annotation.Nullable` in every file that import them
then use (patch-package)[https://github.com/ds300/patch-package] to make a patch file (read the documentation from this library, is easy), also you need to put in your `android/gradle.properties` file the following lines

```
android.useAndroidX=true
android.enableJetifier=true
```

and you are done
`
`

**Comment by Ksiner** [comment]
Check your package.lock file. In my case there was 0.10.16 of rn-fetch-blob instead of 0.10.15, lol.

**Comment by OrlandoRomo** [comment]
It's works dude, thanks for you time and as you said, the package-lock.json had the version 0.10.16 :O

**Comment by brenohq** [comment]
`npm install --save rn-fetch-blob@0.10.15`

solved my problem
