### ISSUE TITLE
plan for npm publishing?

### ISSUE THREAD

**Issue by peacechen** [joltup/rn-fetch-blob#43]
Now that this has been officially forked, is there a plan to publish updates on npm?  Is there a way to gain collaborator access on npm to publish under the same package name?

**Comment by tmaly1980** [comment]
Agreed!

**Comment by Traviskn** [comment]
Right now it is looking like we cannot publish under the same name on NPM.  One option is to publish under the namespace `@joltup/react-native-fetch-blob`, another is to rename the project to something new.  

Any ideas/opinions on which option would be better?

**Comment by Traviskn** [comment]
we are now published to npm as `rn-fetch-blob`, this should stay consistent with how the classes are defined throughout the code as RNFetchBlob
