### ISSUE TITLE
RNFetchBlob.fs.stat error when taking photo on android

### ISSUE THREAD

**Issue by mlapeter** [joltup/rn-fetch-blob#430]
Getting the following on android from uri returned by react-native-image-picker when I choose take photo vs selecting from device: `failed to stat path null because it does not exist or it is not a folder`

Example uri: `content://com.company.myapp.debug.provider/external_files/Pictures/image-a9974a04-f517-4b24-8183-71d5c4373fdd.jpg`

Images already on device work fine, and I'm able to `RNFetchBlob.wrap` and upload the image using FormData fine, it's just fs.stat when taking a photo. 

Version: 0.10.15

**Comment by mlapeter** [comment]
Resolved this by using `path` supplied by react-native-image-picker instead.

**Comment by vikas6377297826** [comment]
I am using react-native-document-picker and get  **Error: failed to stat path `null` because it does not exist or it is not a folder** i try all methods but I still not solve

**Comment by hsnMoghadasi** [comment]
> @vikas6377297826 try setting the following in options `{copyTo : "cachesDirectory" }`, this will copy the file & generate an absolute path which can be accessed from `fileCopyUri` in response.

that correct, but fileCopyUri will be null when the phone memory is full :/
