### ISSUE TITLE
Android User-Agent set to okhttp/3.12.1

### ISSUE THREAD

**Issue by thijs-qv** [joltup/rn-fetch-blob#445]
Info:
rn-fetch-blob version 0.11.2
react-native version 0.60.5
platform: Android

I am retrieving images from a server, this server checks for a specific user agent, if the user agent does not match it will redirect. 
I am setting the user agent via the options object, like so:
`RNFetchBlob.fetch('GET', url, {'User-Agent': myUserAgent})`

On iOS the images can be retrieved (the custom user agent is sent with the request), but on Android the user agent being sent is `okhttp/3.12.1`, which means the server will redirect and I won't be able to retrieve the images.

Note: This only seems to happen for the images. Request to the API itself do have the custom user agent.

**Comment by thijs-qv** [comment]
Edit: Never mind. RNFetchBlob sets the user-agent correctly. It is the Image component from React Native itself which has the okhttp user agent.

**Comment by devWaleed** [comment]
I am facing this issue. I want to download the following map tile image: https://c.tile.openstreetmap.org/12/2811/1755.png. Its working fine in iOS but on Android I am getting 403 forbidden error. This tile server requires User-Agent to be set properly.

EDIT: If I set it to download image from some other server like: https://www.android.com/static/img/transfer.png It works fine.

@thijs-qv

**Comment by thijs-qv** [comment]
You can use an okhttp interceptor to change the user agent for all okhttp requests
