### ISSUE TITLE
Downloading and opening ASCII text file

### ISSUE THREAD

**Issue by thijs-qv** [joltup/rn-fetch-blob#452]
I am using:
React Native 0.61.1
rn-fetch-blob 0.11.2

(iOS, haven't tried Android yet)
I am downloading a text file, but when I try to open it with RNFetchBlob.ios.openDocument() I get the error "document is not supported". I'm using the returned filepath as an argument for openDocument. If I remove the "fileCache: true" from options, I get the file data back, and can see the text.

I'm using an iOS simulator. Checking the returned filepath manually shows that the file exists at the path, with the correct data inside.

Trying with a PDF instead of a plain text file gives the same result.

Any idea's?

**Comment by thijs-qv** [comment]
Further information:
`[UIDocumentInteractionController presentPreviewAnimated:YES]` is returning NO. 
I put a breakpoint in the delegate method `documentInteractionControllerViewControllerForPreview` but it is not being triggered when trying to open the document.

**Comment by thijs-qv** [comment]
I have found the issue: seems that **an extension is required** for `[UIDocumentInteractionController presentPreviewAnimated:YES]` to work. Would be nice if this can be added to the docs.

**Comment by swathi2378** [comment]
@thijs-qv Hi,

I am facing the same issue. Can you please explain in details how did u solve it in js side

**Comment by thijs-qv** [comment]
Try saving the file with the correct file extension, and then opening it.

**Comment by rechard25846** [comment]
@swathi2378 is it because you file contain of special characters or space in between? 
And have u resolved the issue already?
