### ISSUE TITLE
IOS 13 - Open File Issue

### ISSUE THREAD

**Issue by burhan3759** [joltup/rn-fetch-blob#453]
Cannot view the downloaded file on IOS 13, iphone 11

1. It only show the file name and extension type
2. did not display the image / pdf
3. previously with ios 12 working fine

Help guys.. urgent issue.. crying...

**Comment by MichelBahl** [comment]
For me it works on device but not in simulator.

**Comment by burhan3759** [comment]
@MichelBahl Thanks man, yeah i google out and found out the simulator is the issue. and apple fix this bug in beta version 5 if i am not wrong. I think this issue can be closed..
