### ISSUE TITLE
null is not an object (evaluating 'RNFetchBlob.DocumentDir') using Expo

### ISSUE THREAD

**Issue by n1777** [joltup/rn-fetch-blob#516]
I'm using Expo and try to download files using react-native-fetch-blob

```
import RNFetchBlob from 'rn-fetch-blob';

RNFetchBlob.fetch('GET', 'http://www.example.com/images/img1.png')
  .then((res) => {
    let status = res.info().status;
  })
  .catch((errorMessage, statusCode) => {
  })
```

There is an error occurs: null is not an object (evaluating 'RNFetchBlob.DocumentDir')

What i've already tried:

```
npm install --save react-native-fetch-blob
react-native link 
```
```
npm install --save react-native-fetch-blob
react-native link react-native-fetch-blob
```

```
var RNFetchBlob = require('rn-fetch-blob').default
```

```
RNFB_ANDROID_PERMISSIONS=true react-native link
```

How to fix this issue? Does rn-fetch-blob work with Expo?

**Comment by Traviskn** [comment]
https://github.com/joltup/rn-fetch-blob/issues/517#issuecomment-573483891

**Comment by jopsyvarghese** [comment]
You cannot use RNFetchBlob in an Expo managed project as it requires deep linking. Try using expo-file-system instead.
