### ISSUE TITLE
rn-fetch-blob fetch stopped working on iOS

### ISSUE THREAD

**Issue by keremoge** [joltup/rn-fetch-blob#543]
## I use rn-fetch-blob v0.12.0 and today I faced this critical error on iOS;
* Android working fine but in iOS my app no longer seems to request to my servers.
* I didnt change any client or server code. It just stopped working.
* I use React-native v0.59.10, I also tried rn-fetch-blob v0.10.15 but no luck.
* My code snippet is below;
```
const Fetch = RNFetchBlob.polyfill.Fetch;
// replace built-in fetch
const myFetch = new Fetch({
  // enable this option so that the response data conversion handled automatically
  auto: false,
  trusty: true,
  // when receiving response data, the module will match its Content-Type header
  // with strings in this array. If it contains any one of string in this array,
  // the response body will be considered as binary data and the data will be stored
  // in file system instead of in memory.
  // By default, it only store response data to file system when Content-Type
  // contains string `application/octet`.
  binaryContentTypes: [
    'image/',
    'video/',
    'audio/',
    'foo/'
  ]
}).build();

GLOBAL.tmpFetch = myFetch;
GLOBAL.fetch = function (uri, options, ...args) {
  let d = new Date();
  const startTime = d.getTime();
  return GLOBAL.tmpFetch(uri, options, ...args).then((response) => {
    d = new Date();
    const endTime = d.getTime();
    console.log(`Fetch => ${uri} {${endTime - startTime} ms}`, {
      request: {
        uri,
        options,
        ...args,
      },
      response,
    });
    return response;
  }).catch(error => error);
};
```

**Comment by keremoge** [comment]
The problem was the app dynamics that I added 1 year ago. There is a bug on app dynamics server that blocks all request from the client when using rn-fetch-blob

**Comment by teo029** [comment]
@keremoge were you testing RN 0.62 beta or something, because it might be an issue with Flipper and the AppD agent?

**Comment by keremoge** [comment]
No, it's not about Flipper or RN version. There was a bug in the version of AppDynamics. when the usage limit exceeds it's blocking all requests instead of just not logging them. We just updated AppDynamics at serverside. It is working fine right now.

**Comment by Rickyarians** [comment]
@keremoge Hi, have you solved this problem, or are you still getting an error? If it's solved, could you please explain which version I need to install in my project?

**Comment by keremoge** [comment]
> @keremoge Hi, have you solved this problem, or are you still getting an error? If it's solved, could you please explain which version I need to install in my project?

Hi, new appdynamics and rn-fetch-blob versions working fine
