### ISSUE TITLE
value for title cannot be cast from readablenativemap to string

### ISSUE THREAD

**Issue by Shrroy** [joltup/rn-fetch-blob#547]
- "rn-fetch-blob": "^0.10.15",
- "react": "16.8.3",
- "react-native": "^0.59.10",

```js
  let options = {
            fileCache: true,
            appendExt : ext,
            IOSBackgroundTask: true,
            trusty : true,
            addAndroidDownloads : {
                useDownloadManager : true,
                notification : true,
                path:  fs.dirs[path] +"/"+row.fileName.slice(0, row.fileName.length -5)+'_'+Math.floor(date.getTime() + date.getSeconds() / 2)+'.'+ext,
                description : row.fileType.slice(0, 5),
                mime: row.fileType,
            }
        };

        config(options).fetch('GET', linkDownload ).then((res) => {
            console.log(res)
        }).catch((e) => {
            console.log(e)
        });
```
I'm getting this error

> value for title cannot be cast from readablenativemap to string

if I change `fetch` to this 
```js
fetch(linkDownload, {
    method: 'GET',
  })
```
I will get different error this 

> com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String

Can anybody help me with this? thank you for your time.

**Comment by Shrroy** [comment]
I fixed the problem, the url wasn't a string

**Comment by asgaraliyev** [comment]
> * "rn-fetch-blob": "^0.10.15",
> * "react": "16.8.3",
> * "react-native": "^0.59.10",
> 
> ```js
>   let options = {
>             fileCache: true,
>             appendExt : ext,
>             IOSBackgroundTask: true,
>             trusty : true,
>             addAndroidDownloads : {
>                 useDownloadManager : true,
>                 notification : true,
>                 path:  fs.dirs[path] +"/"+row.fileName.slice(0, row.fileName.length -5)+'_'+Math.floor(date.getTime() + date.getSeconds() / 2)+'.'+ext,
>                 description : row.fileType.slice(0, 5),
>                 mime: row.fileType,
>             }
>         };
> 
>         config(options).fetch('GET', linkDownload ).then((res) => {
>             console.log(res)
>         }).catch((e) => {
>             console.log(e)
>         });
> ```
> 
> I'm getting this error
> 
> > value for title cannot be cast from readablenativemap to string
> 
> if I change `fetch` to this
> 
> ```js
> fetch(linkDownload, {
>     method: 'GET',
>   })
> ```
> 
> I will get different error this
> 
> > com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
> 
> Can anybody help me with this? thank you for your time.

i cant see rn-fetch-blob codes .how you can download file without rn-fetch-blob?

**Comment by asgaraliyev** [comment]
> * "rn-fetch-blob": "^0.10.15",
> * "react": "16.8.3",
> * "react-native": "^0.59.10",
> 
> ```js
>   let options = {
>             fileCache: true,
>             appendExt : ext,
>             IOSBackgroundTask: true,
>             trusty : true,
>             addAndroidDownloads : {
>                 useDownloadManager : true,
>                 notification : true,
>                 path:  fs.dirs[path] +"/"+row.fileName.slice(0, row.fileName.length -5)+'_'+Math.floor(date.getTime() + date.getSeconds() / 2)+'.'+ext,
>                 description : row.fileType.slice(0, 5),
>                 mime: row.fileType,
>             }
>         };
> 
>         config(options).fetch('GET', linkDownload ).then((res) => {
>             console.log(res)
>         }).catch((e) => {
>             console.log(e)
>         });
> ```
> 
> I'm getting this error
> 
> > value for title cannot be cast from readablenativemap to string
> 
> if I change `fetch` to this
> 
> ```js
> fetch(linkDownload, {
>     method: 'GET',
>   })
> ```
> 
> I will get different error this
> 
> > com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
> 
> Can anybody help me with this? thank you for your time.

Sorry.I cant see your rn-fetch-blob codes .can I download any file without rn-fetch-blob?

**Comment by Piyush132000** [comment]
Hlo I am also getting same error value for title cannot be cast from readablenativemap to string

if any one know answer please reply
