### ISSUE TITLE
Ios: Failed to create directory, don’t have permission to save the file

### ISSUE THREAD

**Issue by DjailinVasu** [joltup/rn-fetch-blob#549]
-    rn-fetch-blob: ^0.12.0,
-    react: 16.9.0,
-    react-native: 0.61.5,

I get pdf-file from server and save with fs.writeFile method to fs.dirs.DownloadDir directory. 
Result file path is: ``${DownloadDir}/${filename}.pdf`;`
So, my code is:
```
RNFetchBlob.fetch(..).then(res => {
      const { fs } = RNFetchBlob;
       let { DownloadDir } = fs.dirs;
      const filePath = `${DownloadDir}/${filename}.pdf `;
      <…>
      fs.writeFile(filePath, res.data, "base64").then(res => {…});
});
```
This works on ios emulators, but failed when I run the application on a real device with ios 13. By default, I can't catch any error. The process of save file dies quietly. 

But if I delete line endings from the received file data as follows:
```
res.data = res.data.replace(/(\r\n|\n|\r)/gm, "");
```
I get the following error:

![AA88DF1A-06D5-4B70-9BF1-5B0E9A1EE812](https://user-images.githubusercontent.com/49210736/75346306-772a3f80-58af-11ea-9aed-9f7c32d04ad3.png)
![CC909F34-5D84-4E44-ADDB-64FE2F1B9150](https://user-images.githubusercontent.com/49210736/75346311-7a253000-58af-11ea-9d9d-4451719e8cb4.png)
![F823C7B7-FDA8-41B3-B693-EAE7D58191FC](https://user-images.githubusercontent.com/49210736/75346315-7b565d00-58af-11ea-8ecc-8b93915d088b.png)

I saw similar access problems in other issues, but could not find a solution.

**Comment by DjailinVasu** [comment]
The issue with iOS has been solved by using DocumentDir. all the other folders from fs.dirs are unavailable for writing files in iOS13

**Comment by fabio-jreis** [comment]
> The issue with iOS has been solved by using DocumentDir. all the other folders from fs.dirs are unavailable for writing files in iOS13

Thanks :)

**Comment by asphyxiar** [comment]
I have this issue on IOS12 even after using DocumentDir. is there any solution to this?
