### ISSUE TITLE
Save Image action on IOS Preview option causes the app to crash without throwing any exception

### ISSUE THREAD

**Issue by chandreu** [joltup/rn-fetch-blob#577]
**Package version:**
"rn-fetch-blob": "^0.10.16"
"react": "16.8.6",
"react-native": "^0.60.5",
 

**My RN-Fetch-Blob code:**
    const dir = Platform.OS === 'ios'
      ? RNFetchBlob.fs.dirs.DocumentDir
      : RNFetchBlob.fs.dirs.DownloadDir;

    RNFetchBlob
      .config({
        // fileCache: true,
        path: `${dir}/${fileName}`,
        addAndroidDownloads: {
          useDownloadManager: true,
          notification: true,
          mime: getMIMEtype(fileName),
          title: fileName,
          description: 'File downloaded by download manager.',
          mediaScannable: true,
          path: `${dir}/${fileName}`,
        }
      })
      .fetch('GET', `https://domain.com/sms/download/NameOfDocument?subdomain=${subdomain}&userId=${userId}&hardDiskFileId=${fileId}&clientKey=${clientKey}`)
      .then((res) => {
        if (Platform.OS === 'ios') {
          RNFetchBlob.ios.previewDocument(res.path());
        } else {
          RNFetchBlob.android.actionViewIntent(res.path(), getMIMEtype(fileName));
        }
      })
      .catch((err) => {
        console.log(err);
      }); };

**Issue:**
When an attachment finished downloading, on IOS you have the preview modal with a list of options to choose from. Copy, Quick View, Save Image, Save to Files, etc. Quick View and Save to Files works fine but not Save Image. Choosing the Save Image option crashes the app instantly. I don't even get any error on the debug console. No idea what's going on. 

Anyone here can help point out what I'm doing wrong with the RN-Fetch-Blob code above?

**Comment by chandreu** [comment]
Foud out the problem was with IOS permission. Adding these two permission to info.plist solved the issue:

  <key>NSPhotoLibraryUsageDescription</key>
  <string>This app requires access to the photo library to save image.</string>
  <key>NSPhotoLibraryAddUsageDescription</key>
  <string>This app requires access to the photo library to save image.</string>

**Comment by Salman18** [comment]
It worked for me also. Thanks @chandreu

**Comment by NeriCodec** [comment]
Its is well, I recommend add this part in README!
