### ISSUE TITLE
Loader issue i am getting ,is it related to webpack ?

### ISSUE THREAD

**Issue by Salman18** [joltup/rn-fetch-blob#580]
ERROR in ./node_modules/rn-fetch-blob/index.js 12:12
Module parse failed: Unexpected token (12:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   AppState,
| } from 'react-native'
> import type {
|   RNFetchBlobNative,
|   RNFetchBlobConfig,

some of them are mentioning this one

URL(https://github.com/joltup/rn-fetch-blob/issues/183#issuecomment-450826541)

**Comment by deltamish** [comment]
Even I am facing this issue

**Comment by Salman18** [comment]
are you using typescript?

**Comment by deltamish** [comment]
I don't believe so. it's just boiler plate code generated by npx. The issue started when I installed react-native-pdf using the preferred line 

npm install react-native-pdf rn-fetch-blob 

Did what was suggested in the comments. For 3 files as FileReader didn't have that block.

**Comment by joeylu** [comment]
any fixes? I initialized an expo project and only install the rn-fetch-blob, as long as I start import it, it gives me this error, points to the index.js line 12

**Comment by abhinavek** [comment]
why closed this issue without any reason ??? i am also facing this issue..

**Comment by ezolla** [comment]
Help :(

**Comment by tylerssn** [comment]
I'm experiencing this is as well.

**Comment by ChillyHoney** [comment]
The same problem

**Comment by priyeshghamandi** [comment]
Facing the same issue. Why is this closed?

**Comment by hamzaASK** [comment]
we need help plz
