### ISSUE TITLE
when i set notification false for download app crash and shows that invalid value for visibility 2.

### ISSUE THREAD

**Issue by kdpadhiyar** [joltup/rn-fetch-blob#588]
![processed](https://user-images.githubusercontent.com/51284428/80455074-b83ede80-8948-11ea-8efd-a7372e04be67.jpeg)
 

help me i want to download file in background hidden mode

**Comment by MandapatiBhavani** [comment]
@kdpadhiyar did you find any solution for this. I too have the same issue. please provide solution if you have any.

**Comment by kdpadhiyar** [comment]
@MandapatiBhavani  its appears because in library's  manifest file there is one permission missing just add it
3ab7ff9
 <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />

or you can use my  fork library  https://github.com/kdpadhiyar/rn-fetch-blob
