### ISSUE TITLE
ios.previewDocument is not working anymore

### ISSUE THREAD

**Issue by igrlk** [joltup/rn-fetch-blob#605]
Hi Everyone! Around two weeks ago previewDocument was broken for me without any packages updates. Before that, I was able to download PDFs and preview them also. Now only an empty file is coming. 

Here is my code:
```
RNFetchBlob.config({
	fileCache: true,
	indicator: true,
	addAndroidDownloads: {
		useDownloadManager: true,
		notification: true,
		mime: 'application/pdf',
		title: `${fileName}`,
		path: `${dirs.DownloadDir}/${fileName}`,
		description: 'Diagnostic result',
	},
})
	.fetch('GET', `${BACKEND_URL}/${url}`, {
		Authorization: `Bearer ${authToken}`,
	})
	.then((res) => {
		const status = res.info().status;

		if (status === 200) {
			RNFetchBlob.fs.writeFile(filePath, res.data, 'base64');
			RNFetchBlob.ios.previewDocument(filePath);
		}
	})
```

I checked and file is being saved correctly in the temporary folder and it's not empty there, but then when I read it with `ios.previewDocument`, the file is **always empty.** in popup which is appearing. After copying it's also empty, in quick-look it's also empty.

`"rn-fetch-blob": "0.11.2"`
`"react-native": "0.61.2"`

**Comment by SMJ93** [comment]
Hi @igrlk, i've been getting this issue randomly on iOS and Android.

- On iOS it just shows an empty PDF (with the title centred).
- On Android it previews the PDF for a split second, before returning to the App and saying "invalid format".

I think it's a problem with your PDF provider.

Have you tried loading a dummy pdf like:

https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

Hope this helps!

**Comment by PointCodeZero** [comment]
I'm experiencing the exact same issue as described by the thread's author. @SMJ93, I tried dummy pdf's as well and the issue still persists, any ideas?

**Comment by SMJ93** [comment]
@PointCodeZero You may need to re install the app and change the pdf file name - we started adding the date to the title which stopped it using the cached file.

**Comment by PointCodeZero** [comment]
I figure out my problem, I was pointing to `RNFetchBlob.fs.dirs.DownloadDir`, but this is only available for Android. Changed to point to `RNFetchBlob.fs.dirs.DocumentDir`.

**Comment by qasimgit** [comment]
@SMJ93 @lucasftcruz 
hey!
i tried everything, pdf preview works really good on IOS simulator but its not working on real device, any idea?
Thanks

**Comment by SMJ93** [comment]
Hey @qasimgit,

I would suggest finding a different library as this has been archived

**Comment by VasantHugar** [comment]
Issue: pdf preview works on IOS simulator but its not working on Physical device. 

Workaround: It worked on both Simulator and Physical  device after changing `ReactNativeBlobUtil.fs.dirs.DownloadDir` to `ReactNativeBlobUtil.fs.dirs.DocumentDir`
