### ISSUE TITLE
Outdated classes description in Wiki page

### ISSUE THREAD

**Issue by KeyboardNerd** [joltup/rn-fetch-blob#63]
**Example 1:**
The documentation for [RNFetchBlobResponse](https://github.com/joltup/react-native-fetch-blob/wiki/Classes#rnfetchblobresponse) states:
> FetchBlobResponse object has the following methods (these method are synchronous, so you might take quite a performance impact if the file is big)

But in fact, the code clearly says that the text() function can return a Promise when the rnfbEncode is 'path'. 
[This line](https://github.com/joltup/react-native-fetch-blob/blob/master/index.js#L390)
`text : () => string | Promise<any>;`

**Example 2:**
The documentation for [RNFetchBlobResponseInfo](https://github.com/wkh237/react-native-fetch-blob/wiki/Classes#rnfetchblobresponseinfo) has rnfbEncode `rnfbEncode : 'path' | 'base64' | 'utf8'`
But in code, the rnfbEncode can also have 'ascii'. 
[This line](https://github.com/wkh237/react-native-fetch-blob/blob/ac0468977be69fdc28cc08221c1fb8131a412a77/types.js#L51)
`rnfbEncode : 'path' | 'base64' | 'ascii' | 'utf8'`

I'm not sure if the Wiki is outdated or text function should actually be a sync function. 
Thanks.

**Comment by lll000111** [comment]
You should be able to edit the Wiki? When I found errors in the original repo (RNFB by wkh237) I simply edited it myself.
