### ISSUE TITLE
can not find the file on android

### ISSUE THREAD

**Issue by nikhilbhawsinka** [joltup/rn-fetch-blob#658]
Have a base 64 from which i want to convert to PDF. I am using run time permission in the following way:

``` const requestFilePermission = async (pdflocation_2,base64data) => {
    console.log(pdflocation_2)
    try {
        const granted = await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
            {
                title: "Give me permission",
                message:
                "I need permission ",
                buttonNeutral: "Ask Me Later",
                buttonNegative: "Cancel",
                buttonPositive: "OK"
            }
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
            RNFetchBlob.fs.writeFile(pdflocation_2,base64data, 'base64')
                .then((res) => {console.log("File : ", res)});
        } else {
            console.log("Permission denied");
        }
    } catch (err) {
        console.warn(err);
    }
}; 
```

Calling this function by passing a location obtained by `let pdfLocation = RNFetchBlob.fs.dirs.CacheDir + '/' + 'test.pdf';`
and a base64 which i have from my backend.
The location obtained looks like: `/data/user/0/com.billinvoicenew/cache/test.pdf`,  and the response of `.then((res) => {console.log("File : ", res)})` is `File :  15363` which means the file has been created but can not find the file on my mobile. Base64 is correct have validated it online. 
Please help

**Comment by nikhilbhawsinka** [comment]
I have also tried `let pdflocation_2 = RNFetchBlob.fs.dirs.DownloadDir + '/' + 'invoicetest.pdf';`,
the location is `/storage/emulated/0/Download/invoicetest.pdf` but still cant find the pdf

**Comment by olup** [comment]
What did you do to resolve your problem ?

**Comment by wanderlust252** [comment]
i have this issue too

**Comment by babyrusa** [comment]
It's not in the Download folder. I clicked around and found them in Files > device name > DCIM
