### ISSUE TITLE
Android 9 Error: mkdir failed to create some or all directories in '/storage/emulated/0/

### ISSUE THREAD

**Issue by Joshmatjjen** [joltup/rn-fetch-blob#690]
Any time i type the Error below,  I get an error :  Error: mkdir failed to create some or all directories in '/storage/emulated/0/

`RNFetchBlob.fs.mkdir(
            RNFetchBlob.fs.dirs.SDCardDir + '/myDownloader',
          );`

"rn-fetch-blob": "^0.12.0",
"react-native": "0.62.2",

PLEASE HELP

**Comment by PedroTrogo** [comment]
are permissions for external storage already granted?

**Comment by Joshmatjjen** [comment]
Yes... It work Well for Android 7.0

**Comment by GunturThunder** [comment]
add permission like this:
                const granted = await PermissionsAndroid.request(
                        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                        {
                            title: "message...",
                            message:
                                "message... " +
                                "message...",
                            buttonNeutral: "message...r",
                            buttonNegative: "No",
                            buttonPositive: "Yes"
                        }
                    );
                    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                        RNFetchBlob.fs.mkdir( RNFetchBlob.fs.dirs.SDCardDir + '/myDownloader/')
                        .then((exist) => {
                            if (!exist) {
                                    RNFetchBlob.fs.mkdir( RNFetchBlob.fs.dirs.SDCardDir + '/myDownloader/');
                                    .then(() => { console.log('file add') })
                                    .catch((err) => { console.log('error',err) })
                            }
                        })
                        .catch((error) => console.log('error', error))
                    }

**Comment by GunturThunder** [comment]
add permissons like this
`const granted = await PermissionsAndroid.request(
                        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                        {
                            title: "message...",
                            message:
                                "message..." +
                                "message...",
                            buttonNeutral: "message...",
                            buttonNegative: "No",
                            buttonPositive: "Yess"
                        }
                    );
                    if (granted === PermissionsAndroid.RESULTS.GRANTED || Platform.OS === "ios") {
                        RNFetchBlob.fs.exists(RNFetchBlob.fs.dirs.SDCardDir + '/myDownloader/')
                        .then((exist) => {
                            if (!exist) {
                                RNFetchBlob.fs.mkdir(RNFetchBlob.fs.dirs.SDCardDir + '/myDownloader/')
                                    .then(() => { console.log('file add') })
                                    .catch((err) => { console.log('error',err) })
                            }
                        })
                        .catch((error) => console.log('error', error))
                    }`

**Comment by GunturThunder** [comment]
add permissions like this, if permission is true then mkdir like:

const granted = await PermissionsAndroid.request(
                        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                        {
                            title: "message...",
                            message:
                                "message...",
                            buttonNeutral: "message..",
                            buttonNegative: "No",
                            buttonPositive: "Yes"
                        }
                    );
                    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                        RNFetchBlob.fs.exists(RNFetchBlob.fs.dirs.SDCardDir + '/myDownloader/')
                        .then((exist) => {
                            if (!exist) {
                                RNFetchBlob.fs.mkdir( RNFetchBlob.fs.dirs.SDCardDir + '/myDownloader/')
                                    .then(() => { console.log('file add') })
                                    .catch((err) => { console.log('error',err) })
                            }
                        })
                        .catch((error) => console.log('error', error))
                    }

**Comment by paulonteri** [comment]
Same issue

**Comment by PedroTrogo** [comment]
try to add requestLegacyExternalStorage in AndroidManifest
`
<manifest ... >

  <application android:requestLegacyExternalStorage="true" ... >
    ...
  </application>
</manifest>
`

**Comment by MAzeem6778** [comment]
Do you find any work around for this?

**Comment by Malik-Usman17** [comment]
Still facing this issue can't create the directory on my device.
