### ISSUE TITLE
App Crashing on android 9/10.

### ISSUE THREAD

**Issue by akshaykatale99** [joltup/rn-fetch-blob#721]
After downloading the file application keeps crashing on android 9/10 even after allowing permissions.

**Comment by labiebhn** [comment]
same issue

**Comment by akshaykatale99** [comment]
Fixed by adding this in AndroidManifest.xml

<application
....
android:requestLegacyExternalStorage="true"

Check this:
https://stackoverflow.com/questions/56821095/android-q-file-mkdirs-returns-false
