### ISSUE TITLE
In react native is this declaration ok

### ISSUE THREAD

**Issue by birurana** [joltup/rn-fetch-blob#756]
const updateData = ( ) => {
        fetch ('http://192.168.1.13:8000/api/articles/${data.id}/' , {
            method: "PUT",
            headers: {
                
                'Content-Type':'application/json'
                
            },
            body:JSON.stringify({title:title, description})
        })
        .then(resp => resp.json()) 
        .then(data => {
            props.navigation.navigate("Home", {data:data}) 
        })
        .catch(error => Alert.alert("Error:", error.message))

**Comment by retyui** [comment]
Hi 
This module is unmentionable ⚠️!  please use fork: https://github.com/RonRadtke/react-native-blob-util

**Comment by birurana** [comment]
Thanks
