### ISSUE TITLE
DocumentDir changed after app update and hence not able to access old version files (files not persisted after app update in ios)

### ISSUE THREAD

**Issue by navjotsing-dhanawat** [joltup/rn-fetch-blob#781]
Hi Folks,

I have used rn-fetch-blob to save and retrive files locally on react native app. So the files are stored in location like below:
```
/var/mobile/Containers/Data/Application/{uuid}/Documents/assets/20220511/file.jpg
Eg:/var/mobile/Containers/Data/Application/BDA27A8D-5B3A-4ADF-BDF6-582DE15191A6/Documents/assets/20220511/file.jpg
```

Base path is given by rn-fetch-blob as below:
```
/var/mobile/Containers/Data/Application/{uuid}/Documents/
```

I am facing issue after updating app, the uuid getting updated and probably the earlier directory getting removed after app update. And not able to retrive file which are created by older version of app.

Please help if anyone faced such issue and found solution for this? 

Scenario:

```
//My App version 1.0.0

// write UTF8 data to file
// File location : /var/mobile/Containers/Data/Application/BDA27A8D-5B3A-4ADF-BDF6-582DE15191A6/Documents/assets/20220511/file.jpg
RNFetchBlob.fs.writeFile(PATH_TO_WRITE, 'foo', 'utf8').then(()=>{ ... })

// Able to read file
RNFetchBlob.fs.readFile(PATH_TO_READ, 'base64').then((data) => { ... })


//After app update to version 2.0.0

// Not able to read file
// Path: /var/mobile/Containers/Data/Application/BDA27A8D-5B3A-4ADF-BDF6-582DE15191A6/Documents/assets/20220511/file.jpg
RNFetchBlob.fs.readFile(PATH_TO_READ, 'base64').then((data) => { ... })
```

RN version: 0.64.2
rn-fetch-blob: "0.12.0"

**Comment by abdullahrehan430** [comment]
@navjotsing-dhanawat  Hey bro how are you ? I am facing the same problem can you please tell me how you resolved this. How to change app version using plist and which version is correct?
