### ISSUE TITLE
Can we use it with expo 

### ISSUE THREAD

**Issue by CodeTerminator007** [joltup/rn-fetch-blob#790]
I'm trying to download a pdf file in the expo mobile app but so far nothing has been achieved can someone help me if i can use this in the expo mobile app

**Comment by bmurdock** [comment]
I'm pretty sure you would have to eject your project from expo in order to use this, but also I believe the expo team is working on their own solution for this.

It has been quite a while since I've used expo, so maybe things have changed.

**Comment by CodeTerminator007** [comment]
Ty it has Beed sovled
