### ISSUE TITLE
Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed.

### ISSUE THREAD

**Issue by Rohitbarate** [joltup/rn-fetch-blob#854]
I am getting this warning that Package "rn-fetch-blob" contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

**Comment by gabriellend** [comment]
What was the solution to this?

**Comment by sudharsanvishnu** [comment]
Im still facing this issue
