### ISSUE TITLE
Error: more than one library with package name 'com.RNFetchBlob'

### ISSUE THREAD

**Issue by PrakashSmaatApps** [joltup/rn-fetch-blob#88]
i got this error today 

Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.RNFetchBlob'

**Comment by tombailey** [comment]
Do you have both this library and the old one (https://github.com/wkh237/react-native-fetch-blob) installed by any chance?

**Comment by PrakashSmaatApps** [comment]
Hey tombailey,
You are correct. Yes both libraries installed in my project. After removing 1 package it's working. Thank You.

**Comment by Traviskn** [comment]
Glad you found a solution!
