### ISSUE TITLE
rn-fetch-blob not working in android 13 and 14

### ISSUE THREAD

**Issue by himanshukr17** [joltup/rn-fetch-blob#882]
In android 13 and above my react native app is not asking for storage permission

below is the code of androidmanifest file
`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
  <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
  <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
  <uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />`

below is the code for asking storage permission 
`const checkPermission = async () => {

        if (Platform.OS === 'ios') {
            downloadFile();
        } else {
            try {
                let granted = await PermissionsAndroid.request(
                    PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                    {
                        title: 'Storage Permission Required',
                        message:
                            'Application needs access to your storage to download File',
                    }
                );
                console.log(granted)
                if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                    // Start downloading
                    downloadFile();
                    // const android = RNFetchBlob.android;
                    // android.actionViewIntent(path, 'application/pdf');
                    console.log('Storage Permission Granted.');
                } else {
                    // If permission denied then show alert
                    Alert.alert('Error', 'Storage Permission Not Granted');
                }
            } catch (err) {
                // To handle permission related exception
                console.log("++++" + err);
            }
        }
    };`

it work fine in android 11 but not working for android 13 and 14 it give never_ask_again in logs for permission

**Comment by Shahfaisal-0304** [comment]
You don't need to ask permission for 13 and above version. 

import { Platform, Alert } from 'react-native';
import { PermissionsAndroid } from 'react-native';
import { version as androidVersion } from 'react-native-device-info';

const handleDownload = async () => {
    if (Platform.OS === 'ios') {
        downloadFile();
    } else {
        const androidAPILevel = parseInt(androidVersion, 10);
        
        if (androidAPILevel >= 33) {  // Android 13 and above
            downloadFile();
        } else {
            try {
                let granted = await PermissionsAndroid.request(
                    PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                    {
                        title: 'Storage Permission Required',
                        message:
                            'Application needs access to your storage to download File',
                    }
                );
                console.log(granted);
                if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                    // Start downloading
                    downloadFile();
                    console.log('Storage Permission Granted.');
                } else {
                    // If permission denied then show alert
                    Alert.alert('Error', 'Storage Permission Not Granted');
                }
            } catch (err) {
                // To handle permission related exception
                console.log("++++" + err);
            }
        }
    }
};

const downloadFile = () => {
    // Implement your file download logic here
    console.log('Downloading file...');
};

**Comment by himanshukr17** [comment]
that's work for me thanks @Shahfaisal-0304
