### ISSUE TITLE
ES6 import breaks, but dynamic require during runtime works

### ISSUE THREAD

**Issue by isaachinman** [joltup/rn-fetch-blob#9]
Hi there! I've also posted this issue at the [main repo](https://github.com/wkh237/react-native-fetch-blob/issues/685).

I've installed RNFetchBlob in my first RN project, and have encountered a weird issue. To install, I did:

    1. yarn add react-native-fetch-blob
    2. react-native link react-native-fetch-blob

I then removed my `Pods` and `build` dirs out of `ios`, did a fresh install, and launched the simulator. I got [this](https://github.com/wkh237/react-native-fetch-blob/issues/553#issuecomment-376800143) yellowbox warning, but besides that everything seemed alright.

My use case is this: checking image file size after a Share Extension calls back to the main application with an image URI.

In short, this code does not work:

    import RNFetchBlob from 'react-native-fetch-blob'

    export default async (images) => {

      images.forEach(async (image) => {

        RNFetchBlob.fs.stat(image.value)
          .then((stats) => console.log('stats: ', stats))
          .catch((err) => { })

      ...etc

But, this code _does_:

    export default async (images) => {

      const RNFetchBlob = require('react-native-fetch-blob').default

      images.forEach(async (image) => {

        RNFetchBlob.fs.stat(image.value)
          .then((stats) => console.log('stats: ', stats))
          .catch((err) => { })

Any idea why this would be the case? It seems the RNFetchBlob module is available at runtime but not app startup, or something like that? For the first snippet of code, my ShareExtension itself crashes, and the main app is not even opened. The error messages are not verbose enough to be helpful:

> <Error>: assertion failed: 17D102: launchd_sim + 63203 [73626DE2-C6D1-3394-9991-3E928BFE8F25]: 0x16

I assume this is down to some incorrect installation, but I have _no_ idea why I can only import the module during runtime.

Crucially, this is not down to ES6/ES5 import style. If I move `const RNFetchBlob = require('react-native-fetch-blob').default` above the function scope so that it is run immediately and not when the function is invoked, again the entire application breaks.

**Comment by Traviskn** [comment]
Hi @isaachinman!
This is a pretty strange issue, in my work app we have no problem with the es6 style imports and the fetch blob module is definitely available at startup.  I'm curious to know what exactly the `ShareExtension` is that you describe, or if there is some kind of non-standard thing going on with how your image processing code is being called.  If you go to a react component in your app and do something like this:

```javascript
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import RNFetchBlob from 'react-native-fetch-blob';

export default class MyComponent Extends Component {
  render() {
    console.log('RNFetchBlob Defined?', RNFetchBlob);
    return (
      <View>
        <Text>Hello World</Text>
      </View>
    );
  }
}
```
What do you see in the debugger console output? I'm curious if you see `undefined` logged out

**Comment by isaachinman** [comment]
> Crucially, this is not down to ES6/ES5 import style. If I move const RNFetchBlob = require('react-native-fetch-blob').default above the function scope so that it is run immediately and not when the function is invoked, again the entire application breaks.

I'm just using ES5 for dynamic imports.

If I do as you suggest, `RNFetchBlob` is defined. It's something about returning to the app context at a later point in time.

The Share Extension is an implementation of [react-native-share-extension](https://github.com/alinz/react-native-share-extension). The extension does not access `RNFetchBlob` in any way.

I'm not sure how to debug this one any further. We can leave this issue open in case someone else encounters the same thing, or we can close it if you prefer.

**Comment by Traviskn** [comment]
I'm not sure how to debug further either.  I think I'll close this issue for now and if more people encounter it we can re-open and re-investigate
